### ISSUE TITLE
can't use trident with bag cosmetics

### ISSUE THREAD

**Issue by Ecilpse** [PluginBugs/Issues-CosmeticsCore#102]
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### Discord tag (optional)

EclipseMC#7777

### What happened?

when player use riptide trident with looking up at the sky, player was blocked.
video : https://youtu.be/y8fQpES0Qqo

### Steps to reproduce the issue

1. Get trident with riptide enchant.
2. wearing backpack cosmetics.
3. use trident

### Server version

Purpur 1.19.2 R0.1 SNAPSHOT

### CosmeticsCore Version

1.0.7 (logs says 1.2.0, but it is actually version 1.0.7)

### ProtocolLib Version

ProtocolLib v5.0.0-SNAPSHOT-b606

### LoneLibs Version

v1.0.23

**Comment by LoneDev6** [comment]
Will be checked
