### ISSUE TITLE
Embrace Paper's new Plugin Loader Framework

### ISSUE THREAD

**Issue by Akiranya** [PluginBugs/Issues-CosmeticsCore#103]
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

Nailm#9364

**It's a special feature request that doesn't request anything new to CosmeticsCore, but it can bring more potential features and more bug-free and cleaner code base in the future. So just take it as a note maybe.**

### Describe the solution you'd like

Paper recently introduced a new Plugin Loader Framework that solved many weird plugin loading issues that been existed for a long time. In the future, the new framework will allow the plugin to better utilise what Mojang has provided such as datapacks, which might be needed by CosmeticsCore to create more fancy features.

### So why it's useful?

I believe most users of ItemsAdder is using Paper fork so embracing this new plugin loader system would fix potential issues in the future. Also, it makes it possible to easily bring cool features that are dedicated to Paper servers.

The new plugin system also allows to decalre the dependencies in a more fine-tuned way. The isolated classloaders are also a cool feature to make use of. Please see the documents for more details :)

As a side note, I guess #73 would have been resolved by this new plugin system (ya #73 already been fixed -  I'm just reminding it so that this feature request make more sense).

### Compatiable with Spigot

As the document says,

> It should be noted you still have the ability to include both paper-plugin.ymland plugin.yml in the same jar.

So for servers using Spigot, they will not be affected by this new plugin loader system at all.

Related PRs:
- https://github.com/PaperMC/Paper/pull/8108
- https://github.com/PaperMC/Paper/pull/8873

Documents:
- https://docs.papermc.io/paper/reference/paper-plugins
- https://docs.papermc.io/paper/dev/getting-started/paper-plugins

### Is your feature request related to a problem?

I believe #73 would have been fixed by the new plugin loader system.

### Describe alternatives you've considered

None

### Additional context

There are more information in the Paper's discord btw.

**Comment by Akiranya** [comment]
Just reliazed that if CosmeticsCore add a `paper-plugin.yml` in the jar resource, the minimum `api-version` must be 1.19

Anyways it's a cool feature for the future. CosmeticsCore can embrace it when it's time to do so.

**Comment by LoneDev6** [comment]
https://github.com/PluginBugs/Issues-CosmeticsCore/issues/73 has nothing to do with the dependencies management.
It was caused by a bug of my plugin.

The new Paper plugin system has no advantage over this, so I'd rather not implement this feature.

I might take it into account for future features which might require cyclic dependencies, but I doubt I'd need that.
Thanks
