### ISSUE TITLE
add blacklist&whitelist world

### ISSUE THREAD

**Issue by oing1215** [PluginBugs/Issues-CosmeticsCore#105]
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

EclipseMC#7777

### Describe the solution you'd like

literally. can you add blacklist&whitelist world? 

### Is your feature request related to a problem?

i'd like disable cosmetics features in minigame, parkour world because of the sight.

### Describe alternatives you've considered

,

**Comment by LoneDev6** [comment]
Added!
```yml
  worlds:
    - "world"
    - "world_nether"
```

You can specify wildcards too.
```yml
  worlds:
    - "*"
```

```yml
  worlds:
    - "world_*"
```
