### ISSUE TITLE
two bugs with ballon cosmetics

### ISSUE THREAD

**Issue by oing1215** [PluginBugs/Issues-CosmeticsCore#106]
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### Discord tag (optional)

EclipseMC#7777

### What happened?

i use lastest version of cosmeticscore (1.2.0b) after update, some bugs are happend
video : https://youtu.be/xdnTtq-xMww
1. part of ballon's leash are invisible
2. when player sit chair with ballon, (items adders furnitrues) player sitting in the air.
3. also player was moved to air when teleport.

### Steps to reproduce the issue

equip ballon cosmetics -> teleport, sitdown, and look balloon's strap.

### Server version

purpur 1.19.2 ro.1

### CosmeticsCore Version

1.2.0b

### ProtocolLib Version

ProtocolLib v5.0.0-SNAPSHOT-b606

### LoneLibs Version

v1.0.23

**Comment by LoneDev6** [comment]
> part of ballon's leash are invisible

Fix it by moving the bone a bit more up using Blockbench, it's normal if the leash bone are not correctly configured.
https://cosmeticscore.devs.beer/adding-content/balloon/leash-location

> when player sit chair with ballon, (items adders furnitrues) player sitting in the air.

i don't understand

> also player was moved to air when teleport.

i don't understand


please post a video, the link you shared doesn't work.
use streamable https://streamable.com/ youtube is too slow to upload videos.
