### ISSUE TITLE
balloon leash is invisible

### ISSUE THREAD

**Issue by oing1215** [PluginBugs/Issues-CosmeticsCore#112]
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### Discord tag (optional)

EclipseMC#7777

### What happened?

after update 1.0.7 to 1.2.0b, balloon cosmetics leash is invisible.
and y-coordinate is set abnormally when the player executes the spawn command or sits on the chair with equip balloon cosmetics.

### Steps to reproduce the issue

1. equip balloon cosmetics
2. look balloon cosmetics itself

1. equip balloon cosmetics
2. sit chair on execute spawn command

### Server version

purpur 1.19.2 Ro.1

### CosmeticsCore Version

1.2.0b

### ProtocolLib Version

5.0.0-SNAPSHOT-b615

### LoneLibs Version

1.0.23

### Screenshots/Videos (you can drag and drop files or paste links)

[1.0.7]
![2023-03-21_07 07 28](https://user-images.githubusercontent.com/126366825/226477206-a55d5514-10a3-42b2-9e92-1f7dac1981d3.png)
![2023-03-21_07 10 02](https://user-images.githubusercontent.com/126366825/226477211-4cce79cb-57cd-4a3d-bdbd-670696951b32.png)

[1.2.0b]
![2023-03-21_07 09 27](https://user-images.githubusercontent.com/126366825/226477259-e8cce8d5-47fc-48cb-9934-dee9c4f706a0.png)
![2023-03-21_07 08 08](https://user-images.githubusercontent.com/126366825/226477267-c080e748-8cd8-4add-b0b2-1c3baa87a023.png)

**Comment by dinobossytnew** [comment]
It is being tested to replicate the possible bug, using the plugin's default models.

**Comment by dinobossytnew** [comment]
Try to update to the new version 1.2.1, whenever you report a possible bug use the latest version because it is not happening to me.

Do you use a special plugin for seating or do you use normal funitures from itemsadders?

**Comment by LoneDev6** [comment]
always update to the latest version before reporting issues, thanks
