### ISSUE TITLE
Request to add boarding plug-in compatibility

### ISSUE THREAD

**Issue by cats-love** [PluginBugs/Issues-CosmeticsCore#116]
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

cats#0935

### Describe the solution you'd like

https://www.spigotmc.org/resources/playerrider.62799/

Request compatibility with the boarding functionality of the plug-in. There's a bug where I sit down after summoning the entrance ceremony with a cosmetic plug-in and it doesn't come down

### Is your feature request related to a problem?

yes

### Describe alternatives you've considered

What should I do? Or what other boarding plugins are there?

**Comment by cats-love** [comment]
![2023-04-01_20 16 53](https://user-images.githubusercontent.com/87476958/229286379-0abb6803-c263-4483-8c16-86933966d82d.png)

**Comment by LoneDev6** [comment]
Try this
https://www.spigotmc.org/resources/gsit-modern-sit-seat-and-chair-lay-and-crawl-plugin-1-13-x-1-19-x.62325/

I tested it and worked fine.
