### ISSUE TITLE
Disable on PvP

### ISSUE THREAD

**Issue by adabugra** [PluginBugs/Issues-CosmeticsCore#129]
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Describe the solution you'd like

Adding a config option or that disables all cosmetics when they enter combat.

### Is your feature request related to a problem?

No

### Describe alternatives you've considered

Maybe a CombatLogX integration

**Comment by LoneDev6** [comment]
I can add this option in a future update

**Comment by WhiteProject1** [comment]
DeluxeCombat support its important to
