### ISSUE TITLE
How to correctly adjust the position of self perspective model

### ISSUE THREAD

**Issue by axin0452** [PluginBugs/Issues-CosmeticsCore#13]
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

POGR#2334

### Describe the solution you'd like

![image](https://user-images.githubusercontent.com/39695561/191083608-fd4f45a5-1cf7-4849-aec9-ff207cf0fed5.png)
![image](https://user-images.githubusercontent.com/39695561/191083673-d126d287-7ace-4ae3-933e-25931ac31b82.png)
![image](https://user-images.githubusercontent.com/39695561/191091795-ffab3bd6-d516-43fb-87e7-0123e02e04f7.png)

As shown in the figure, the Y axis of the self model has been adjusted to the lowest, but the position of the player model cannot be displayed correctly, it may be a problem with the model file. I don't know

But the normal model can be adjusted to the perfect position. 
![image](https://user-images.githubusercontent.com/39695561/191091655-c5a2feba-2d19-430f-8f83-a8474ae7b7f5.png)

### Is your feature request related to a problem?

Can you add a function to further adjust the model position in the plug-in configuration file

### Describe alternatives you've considered

。。

**Comment by LoneDev6** [comment]
You have to move it down also in the main model view, in the edit mode.
This happens only on some models because of their size/position in the edit view.
 Check the tutorial: https://lonedev.gitbook.io/cosmeticscore/adding-content/body-item/static-body-item/normal-and-self-models#step-4

Video: 
https://www.youtube.com/watch?v=dmQI35Xd4Js

**Comment by axin0452** [comment]
![image](https://user-images.githubusercontent.com/39695561/191098866-da268ecb-b51a-4e97-a496-3fbea174b313.png)

@LoneDev6 
I have changed according to the tutorial provided by you and can no longer go down. But at this time, the location of the model is still wrong. Many models have such problems. Do I want to change all the model styles, not only the location, but also the appearance of many models need to be changed to look beautiful. Otherwise, the display of those models is problematic

**Comment by LoneDev6** [comment]
I really don't understand your report.

The issue is that it seems you're moving the model in the wrong way.
This cannot be automated because each artist has modelled cosmetics in a different way, that's why you have to do it yourself for each model.
Please watch my video to understand.

You have to test a few times until you reach the correct height location.

**Comment by axin0452** [comment]
@LoneDev6 
I completely follow your video tutorial to move down. I can no longer move down. I do not automate. I move down each model according to the tutorial. If I automate, why does the default model display correctly? I have debugged it for many times, and it can no longer move down. Does the machine translation affect my description? Let me not fully express my meaning

**Comment by LoneDev6** [comment]
Send here your backpack JSON model and PNG, I will try to help

**Comment by axin0452** [comment]
[body.zip](https://github.com/PluginBugs/Issues-CosmeticsCore/files/9606731/body.zip)
@LoneDev6  Thank you.

**Comment by LoneDev6** [comment]
I updated the tutorial, thanks for the help!
https://lonedev.gitbook.io/cosmeticscore/adding-content/body-item/static-body-item/normal-and-self-models

File: [coal_pack_self.zip](https://github.com/PluginBugs/Issues-CosmeticsCore/files/9607553/coal_pack_self.zip)
