### ISSUE TITLE
Cosmetics for pvp

### ISSUE THREAD

**Issue by adabugra** [PluginBugs/Issues-CosmeticsCore#130]
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Describe the solution you'd like

A feature that adds arrow, death and maybe pet cosmetics.

### Is your feature request related to a problem?

No

### Describe alternatives you've considered

.

**Comment by LoneDev6** [comment]
This is out of scope, this is a cosmetics plugin and it's not meant to be used for pvp.
The plugin itself has a very easy to use API you can hook into to integrate some custom behaviour.
