### ISSUE TITLE
Balloon leash displaying incorrectly

### ISSUE THREAD

**Issue by MrStreeet** [PluginBugs/Issues-CosmeticsCore#131]
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### Discord tag (optional)

RXJyZWJl?#1037

### What happened?

Basically my ballons are displaying weirdly, with MEG and IA system, the leash it's not attached correctly to the ballon, I tried to update the plugins and same, it doesn't works.

I asked in the Discord of the community and looks like it's a bug from the latest version 1.19.4.

Also, the ballon pushes you meanwhile.

### Steps to reproduce the issue

1. Install default pack with IA dependencie.
2. Go to wardrobe
3. Choose ballon

### Server version

This server is running Paper version git-Paper-516 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: f7717c3)
You are running the latest version
Previous version: git-Paper-510 (MC: 1.19.4)

### CosmeticsCore Version

CosmeticsCore version 1.2.2

### ProtocolLib Version

PrtocolLib version 5.0.0-SNAPSHOT-636

### LoneLibs Version

LoneLibs version 1.0.24

### CosmeticsCore config.yml

```shell
lang: en
extract_default_assets: true
cosmetics:
  max_equippable:
    body: 1
    balloon: 1
wardrobe_room:
  camera:
    hide_actionbar_texts: true
    rotation:
      enabled: true
    zoom:
      enabled: true
      min: 2
    fade_effect: true
    location:
      world: world
      x: 76.0
      y: 67.3
      z: -133.0
      yaw: 45.29826
      pitch: 0.75012827
  mannequin:
    location:
      world: world
      x: 73.46578795976072
      y: 66.0
      z: -130.55074367914733
      yaw: -178.80142
      pitch: -2.549582
  teleport_area:
    enter:
      world: world
      pos1:
        x: 71.0
        y: 66.0
        z: -134.0
      pos2:
        x: 76.0
        y: 69.0
        z: -134.0
    exit_location:
      world: world
      x: 77.5
      y: 66.0
      z: -138.5
      yaw: -90.0009
      pitch: 2.549916
  gui:
    cursor_default: fermented_spider_eye:9000001
    cursor_rotate: fermented_spider_eye:9000002
    cursor_pointer: fermented_spider_eye:9000003
    dyeing_pointer: fermented_spider_eye:9100003
    tutorial_gui: fermented_spider_eye:9100004
    tutorial_gui_checked: fermented_spider_eye:9100005
    slots:
      colors:
        not_owned: 195,147,57
        owned: 56,67,100
        wearing: 57,70,195
        wearing_preview: 195,120,57
        max_amount_reached: 111,111,111
      add_item_in_blank_slots:
        # This is useful only for some expert users that need to do some crazy stuff.
        # Do not enable it if you don't know what you are doing.
        enabled: false
        type: PAPER
        custom_model_data: 1337666
send_creative_hidden_hat_message: true
save:
  # Use only one at a time
  file:
    enabled: true
  mysql:
    enabled: false
    url: jdbc:mysql://my_url_database_69.com:3306/database_name
    username: username
    password: password
    table: cosmeticscore_saved
debug: false
```

### Screenshots/Videos (you can drag and drop files or paste links)

https://i.gyazo.com/4bc56d0ab940cdeb4d744c55e4d74cd5.gif

**Comment by LoneDev6** [comment]
Thanks, this will be checked as soon as possible.

Sorry for the delay, as I [previously announced](https://forum.devs.beer/d/298-inactivity-march-2023) I was on a little vacancy the previous week to rest and be ready to help you all better than before!
Thanks a lot for the patience.

**Comment by LoneDev6** [comment]
Fixed in the upcoming update.


![Image](https://github.com/PluginBugs/Issues-CosmeticsCore/assets/27242001/b74ab059-0e85-4916-a1ac-1af5c2cdad32)



I also updated the tutorial: https://cosmeticscore.devs.beer/adding-content/balloon/leash-location
