### ISSUE TITLE
Display name duplicating

### ISSUE THREAD

**Issue by Koudyasek** [PluginBugs/Issues-CosmeticsCore#138]
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### Discord tag (optional)

Koudy#5934

### What happened?

When I randomly click in deluxe menus gui, the display name is duplicating https://prnt.sc/QA7E4vtaPSb8

### Steps to reproduce the issue

described above

### Server version

[14:16:42 INFO]: Current: git-Purpur-1976 (MC: 1.19.4)*
Previous: git-Paper-538 (MC: 1.19.4)
* You are running the latest version

### CosmeticsCore Version

version CosmeticsCore
[14:21:48 INFO]: CosmeticsCore version 1.2.2d

### ProtocolLib Version

[14:22:06 INFO]: ProtocolLib version 5.0.0-SNAPSHOT-642
[14:22:06 INFO]: Provides read/write access to the Minecraft protocol.
[14:22:06 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

[14:22:18 INFO]: LoneLibs version 1.0.24
[14:22:18 INFO]: Collection of libs used by my plugins
[14:22:18 INFO]: Authors: LoneDev and others

### FULL server log

//// if needed, please contact me.

### Error (optional)

```shell
no errors
```

### CosmeticsCore config.yml

```shell
lang: en
extract_default_assets: true
cosmetics:
  max_equippable:
    body: 1
    balloon: 1
wardrobe_room:
  camera:
    hide_actionbar_texts: true
    rotation:
      enabled: true
    zoom:
      enabled: true
      min: 2
    fade_effect: true
    location:
      world: flat
      x: 205
      y: -58.5
      z: 41
      yaw: 359.85
      pitch: 6.6
  mannequin:
    location:
      world: flat
      x: 204.5
      y: -60
      z: 45.5
      yaw: 180
      pitch: 0
  teleport_area:
    enter:
      world: flat
      pos1:
        x: 167
        y: -61
        z: 42
      pos2:
        x: 167
        y: -57
        z: 37
    exit_location:
      world: flat
      x: 164
      y: -60
      z: 40
      yaw: 98
      pitch: 10
  gui:
    cursor_default: fermented_spider_eye:9000001
    cursor_rotate: fermented_spider_eye:9000002
    cursor_pointer: fermented_spider_eye:9000003
    dyeing_pointer: fermented_spider_eye:9100003
    tutorial_gui: fermented_spider_eye:9100004
    tutorial_gui_checked: fermented_spider_eye:9100005
    slots:
      colors:
        not_owned: 195,147,57
        owned: 56,67,100
        wearing: 57,70,195
        wearing_preview: 195,120,57
        max_amount_reached: 111,111,111
      add_item_in_blank_slots:
        # This is useful only for some expert users that need to do some crazy stuff.
        # Do not enable it if you don't know what you are doing.
        enabled: false
        type: PAPER
        custom_model_data: 1337666
send_creative_hidden_hat_message: true
save:
  # Use only one at a time
  file:
    enabled: true
  mysql:
    enabled: false
    url: jdbc:mysql://my_url_database_69.com:3306/database_name
    username: username
    password: password
    table: cosmeticscore_saved
debug: false
```

### Problematic items yml configuration file (optional)

```shell
////
```

### Other files, you can drag and drop them here to upload. (optional)

///

### Screenshots/Videos (you can drag and drop files or paste links)

Above

**Comment by Koudyasek** [comment]
Hello, also I have issue that we have creative server and after removing the cosmetics I can grab the item (the item is not removed)

**Comment by LoneDev6** [comment]
Does this happen only with deluxemenu?

**Comment by Koudyasek** [comment]
> Does this happen only with DeluxeMenus? Please provide a configuration for DeluxeMenus for me to test.

Hello, can you please contact me at discord, so I can provide it to you?
about if it is only with DeluxeMenus, tbh not sure. This is the only what I found for now.
