### ISSUE TITLE
Resource pack loading breaks wardrobe mode.

### ISSUE THREAD

**Issue by Jeck** [PluginBugs/Issues-CosmeticsCore#139]
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### What happened?

If the player is in wardrobe mode when a resource pack gets sent, they'll remain an invisible player unable to shift-exit forever. Wardrobe mannequin remains, mouse gui works, but player can walk around.

### Steps to reproduce the issue

1. Go into /wardrobe
2. Server operator sends a new resource pack (check out forcepack plugin, but I think there's ways to do this in vanilla)
3. User downloads resource pack, loses wardrobe UI but remains invisible, can't shift-to-exit

### Server version

This server is running Paper version git-Paper-538 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: bcd8dc2)
You are 2 version(s) behind
Download the new version at: https://papermc.io/downloads/paper

### CosmeticsCore Version

CosmeticsCore version 1.2.2.d

### ProtocolLib Version

5.0.0

### LoneLibs Version

1.0.24

### FULL server log

No errors in log. Long server uptime means log is too big, I can reproduce a clean log file again later if needed, but again there's no java errors at all within it.

### CosmeticsCore config.yml

```shell
lang: en
extract_default_assets: true
cosmetics:
  max_equippable:
    body: 3
    balloon: 2
wardrobe_room:
  camera:
    hide_actionbar_texts: true
    rotation:
      enabled: true
    zoom:
      enabled: true
      min: 2
    fade_effect: true
    location:
      world: dungeonworld
      x: 205
      y: -58.5
      z: 41
      yaw: 359.85
      pitch: 6.6
  mannequin:
    location:
      world: dungeonworld
      x: 204.5
      y: -60
      z: 45.5
      yaw: 180
      pitch: 0
  teleport_area:
    enter:
      world: dungeonworld
      pos1:
        x: 167
        y: -61
        z: 42
      pos2:
        x: 167
        y: -57
        z: 37
    exit_location:
      world: dungeonworld
      x: 164
      y: -60
      z: 40
      yaw: 98
      pitch: 10
  gui:
    cursor_default: fermented_spider_eye:9000001
    cursor_rotate: fermented_spider_eye:9000002
    cursor_pointer: fermented_spider_eye:9000003
    dyeing_pointer: fermented_spider_eye:9100003
    tutorial_gui: fermented_spider_eye:9100004
    tutorial_gui_checked: fermented_spider_eye:9100005
    slots:
      colors:
        not_owned: 195,147,57
        owned: 56,67,100
        wearing: 57,70,195
        wearing_preview: 195,120,57
        max_amount_reached: 111,111,111
      add_item_in_blank_slots:
        # This is useful only for some expert users that need to do some crazy stuff.
        # Do not enable it if you don't know what you are doing.
        enabled: false
        type: PAPER
        custom_model_data: 1337666
send_creative_hidden_hat_message: true
save:
  # Use only one at a time
  file:
    enabled: true
  mysql:
    enabled: false
    url: jdbc:mysql://my_url_database_69.com:3306/database_name
    username: username
    password: password
    table: cosmeticscore_saved
debug: false
```

### Screenshots/Videos (you can drag and drop files or paste links)

![image](https://github.com/PluginBugs/Issues-CosmeticsCore/assets/994258/1c5e3b40-e05d-4822-a002-8cab91517f98)

**Comment by Jeck** [comment]
Screenshot is in pause menu, sorry, but you can see player's mannequin and cursor in top right.

**Comment by LoneDev6** [comment]
Make a video please, thanks

**Comment by LoneDev6** [comment]
Why are you sending resourcepacks while players are in the wardrobe?
