### ISSUE TITLE
Event API for EnteredWardrobeDoorEvent, cancel to enter wardrobe 🙀

### ISSUE THREAD

**Issue by lastsurvivors** [PluginBugs/Issues-CosmeticsCore#142]
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Describe the solution you'd like

Event API to cancel to use

### Is your feature request related to a problem?

i want to have api for **EnterWardrobeDoorEvent**  to prevent bedrock player to enter wardrobe/use cosmetics 

public void bedrockEnterWardrobe(EnterWardrobeDoorEvent e) {
    if(//e.getPlayer() is bedrock user) {
        e.setCancel(true)
    }
}

### Describe alternatives you've considered

more api -3-

**Comment by LoneDev6** [comment]
Implemented EnterWardrobeEvent and ExitWardrobeEvent.
Thanks for the patience!
