### ISSUE TITLE
Clickable slots are missing

### ISSUE THREAD

**Issue by ShizuArt** [PluginBugs/Issues-CosmeticsCore#143]
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### What happened?

Two clickable slots are missing for the body and balloon button (in the blue et neon green spot on the screenshot)

![image](https://github.com/PluginBugs/Issues-CosmeticsCore/assets/98397139/4d25cfd2-25ed-4412-b0b9-ea96d3875c9f)

It's annoying for its own custom GUI

### Steps to reproduce the issue

1. Go in the wardrobe
2. Place your cursor exactly where the two slots remained gray on the screenshot I provided 
3. Click here and nothing happend 

### Server version

This server is running CraftBukkit version 3744-Spigot-d1bd3bd-a7cfc77 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT)

### CosmeticsCore Version

CosmeticsCore version 1.2.2e

### ProtocolLib Version

ProtocolLib version 5.0.0

### LoneLibs Version

LoneLibs version 1.0.24

**Comment by LoneDev6** [comment]
Post your config.yml of CosmeticsCore.
Thanks!

**Comment by ShizuArt** [comment]
https://pastebin.com/agZ4USdd

**Comment by LoneDev6** [comment]
Thanks I'll check this as soon as possible
