### ISSUE TITLE
Support 1.20 & 1.20.1

### ISSUE THREAD

**Issue by DxrkCat** [PluginBugs/Issues-CosmeticsCore#144]
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Describe the solution you'd like

Pending support for new versions

### Is your feature request related to a problem?

NO

### Describe alternatives you've considered

No alternatives

**Comment by LoneDev6** [comment]
1.20.1 support added!
1.20 is old and can't be supported, please update.
