### ISSUE TITLE
Cosmeticscore conflict with ItemsAdder emoji command

### ISSUE THREAD

**Issue by ShizuArt** [PluginBugs/Issues-CosmeticsCore#148]
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### Discord tag (optional)

shizua.

### What happened?

ItemsAdder /emoji command not working when Cosmeticscore is ON

### Steps to reproduce the issue

1. Start your server with ItemsAdder and Cosmeticscore
2. Write /emoji command in chat
3. The emojis book doesn't open
4. Stop your server
5. Start your server with ItemsAdder and whithout Cosmeticscore
6. Write /emoji command in chat
7. The emojis book open

### Server version

This server is running CraftBukkit version 3744-Spigot-d1bd3bd-a7cfc77 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT)

### CosmeticsCore Version

CosmeticsCore version  1.2.2f
ItemsAdder version 3.5.0c-r2

### ProtocolLib Version

ProtocolLib version 5.0.0

### LoneLibs Version

LoneLibs version 1.0.25

### FULL server log

Logs with Cosmeticscore :
[latest.log](https://github.com/PluginBugs/Issues-CosmeticsCore/files/12062245/latest.log)

Logs without Cosmeticscore :
[latest.log](https://github.com/PluginBugs/Issues-CosmeticsCore/files/12062264/latest.log)

### CosmeticsCore config.yml

```shell
lang: en
extract_default_assets: true
cosmetics:
  max_equippable:
    body: 1
    balloon: 1
wardrobe_room:
  camera:
    hide_actionbar_texts: true
    rotation:
      enabled: true
    zoom:
      enabled: false
      min: 2
    fade_effect: true
    location:
      world: world
      x: 18.291798285196077
      y: 206.62000000476837
      z: -0.3699390539944418
      yaw: -92.217224
      pitch: 4.9502816
  mannequin:
    location:
      world: world
      x: 22.402257210595803
      y: 205.0
      z: -0.5209873796033229
      yaw: 90.03286
      pitch: 27.300268
  teleport_area:
    enter:
      world: world
      pos1:
        x: 17.0
        y: 209.0
        z: -3.0
      pos2:
        x: 17.0
        y: 205.0
        z: 1.0
    exit_location:
      world: world
      x: 15.366859120495302
      y: 205.0
      z: -0.5282590743089679
      yaw: 89.882904
      pitch: 13.350279
  gui:
    cursor_default: fermented_spider_eye:9000001
    cursor_rotate: fermented_spider_eye:9000002
    cursor_pointer: fermented_spider_eye:9000003
    dyeing_pointer: fermented_spider_eye:9100003
    tutorial_gui: fermented_spider_eye:9100004
    tutorial_gui_checked: fermented_spider_eye:9100005
    slots:
      colors:
        not_owned: 103,103,103
        owned: 112,82,129
        wearing: 155,222,222
        wearing_preview: 180,180,180
        max_amount_reached: 112,82,129
      add_item_in_blank_slots:
        # This is useful only for some expert users that need to do some crazy stuff.
        # Do not enable it if you don't know what you are doing.
        enabled: false
        type: PAPER
        custom_model_data: 1337666
send_creative_hidden_hat_message: true
save:
  # Use only one at a time
  file:
    enabled: true
  mysql:
    enabled: false
    url: jdbc:mysql://my_url_database_69.com:3306/database_name
    username: username
    password: password
    table: cosmeticscore_saved
debug: false
```

### Screenshots/Videos (you can drag and drop files or paste links)

ItemsAdder /emoji command not working :
![image](https://github.com/PluginBugs/Issues-CosmeticsCore/assets/98397139/91c906f8-160a-42a3-b2d2-0d6c131f503e)

ItemsAdder /emoji command working :
![image](https://github.com/PluginBugs/Issues-CosmeticsCore/assets/98397139/cd5a0be0-254b-414c-be8d-e843e45bffdb)

**Comment by LoneDev6** [comment]
Strange.
This will be checked

**Comment by LoneDev6** [comment]
Can't reproduce the issue.

https://github.com/PluginBugs/Issues-CosmeticsCore/assets/27242001/4aa1924c-cbed-417b-aa5a-5bc0671167af
