### ISSUE TITLE
Ultima versione del plugin - Resourcepack incompleta

### ISSUE THREAD

**Issue by Distolfix** [PluginBugs/Issues-CosmeticsCore#149]
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### What happened?

Ciao, risulta che nell'ultima versione del tuo plugin, la resourcepack sia incompleta. Precisamente: 

[21:57:43 ERROR]: :server: PNG 'z_cosmetics:cosmetics_slot' not found for model. File: /home/container/plugins/ItemsAdder/contents/cosmetics/resourcepack/assets/z_cosmetics/models/cosmetics_slot.json

Adesso ti manderò un video per mostrarti che appunto l'ultima versione del tuo plugin, la resourcepack che tu includi, è incompleta quindi, non è possibile usare il tuo plugin.

### Steps to reproduce the issue

1- Scarica il tuo plugin sul sito 
2- Carica il plugin. 
3- Riavvia il server
4- Scarica la resourcepack sul pc e estri il file zip.
5- Sostituisci i file itemsadder e cosmetics core nella cartella plugins
6- fai /iazip 
7- Guarda la console

### Server version

pufferfish 1.19.4

### CosmeticsCore Version

1.2.2f

### ProtocolLib Version

5

### LoneLibs Version

1.025

**Comment by Distolfix** [comment]
![image](https://github.com/PluginBugs/Issues-CosmeticsCore/assets/73421268/3e3a5db9-fc01-4933-9057-c10664998f3f)


Questa è la cartella della resourcepack scaricata. 

![image](https://github.com/PluginBugs/Issues-CosmeticsCore/assets/73421268/4ed1b6a0-7702-46a5-85eb-e461195df597)

Manca il file gui_light per la precisione. Spero puoi fixxare mi è impossibilitato usare il tuo plugin, esce la texture tutta buggata

**Comment by LoneDev6** [comment]
Il plugin di per se funziona?
Vedi qualche texture/modello ingame che non viene mostrato correttamente?
Perché mi sa che quel cosmetic_slot è un file immagine che non viene più usato dal plugin quindi era stato rimosso, ma probabilmente non ho eliminato anche il modello.

**Comment by Distolfix** [comment]
@LoneDev6 in realtà funziona. L’unica cosa é che non capisco come mai con il badlion le texture per la maggior parte escono buggate. Sono costretto ad usare il lunar client. Quindi in realtà puoi chiuderlo l’unica cosa cancella il modello perché magari poi una persona si ritrova questo errore. Magari se hai delucidazioni al riguardo, sul motivo del perché con il badlion client le texture escono buggate

**Comment by LoneDev6** [comment]
è impossibile aiutarti senza screenshot e log del client + server, i palloncini funzionano correttamente sul mio server di test.
