### ISSUE TITLE
Player tag name is not visible when cosmetic is worn

### ISSUE THREAD

**Issue by rugiaDev** [PluginBugs/Issues-CosmeticsCore#153]
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### Discord tag (optional)

.haejwo

### What happened?

1. player names are not displayed when wearing body cosmetics.  i don't use taglist plugin

2. "aqua_affinity" enchantment does not work when wearing head cosmetics.

### Steps to reproduce the issue

simply put on a cosmetic look and it will appear.

### Server version

This server is running Paper version git-Paper-550 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: 483368e on ver/1.19.4)

### CosmeticsCore Version

CometicsCore version 1.2.2f

### ProtocolLib Version

ProtocolLib version 5.1.0-SNAPSHOT-652

### LoneLibs Version

LoneLibs version 1.0.24

### FULL server log

nothing error log

### CosmeticsCore config.yml

```shell
lang: en
extract_default_assets: true
cosmetics:
  max_equippable:
    body: 2
    balloon: 1
wardrobe_room:
  camera:
    hide_actionbar_texts: true
    rotation:
      enabled: true
    zoom:
      enabled: true
      min: 2
    fade_effect: true
    location:
      world: unified_spawn
      x: -125.62368402798357
      y: 66.9963145471487
      z: -66.49270254313312
      yaw: 135.75098
      pitch: 18.449541
  mannequin:
    location:
      world: unified_spawn
      x: -128.44380012850166
      y: 64.0
      z: -69.95872063258213
      yaw: -0.15066917
      pitch: 9.749842
  teleport_area:
    enter:
      world: unified_spawn
      pos1:
        x: -132.0
        y: 66.0
        z: -65.0
      pos2:
        x: -128.0
        y: 64.0
        z: -65.0
    exit_location:
      world: unified_spawn
      x: -129.52955261214709
      y: 63.0
      z: -61.407298722218044
      yaw: 0.44937134
      pitch: 85.34995
  gui:
    cursor_default: fermented_spider_eye:9000001
    cursor_rotate: fermented_spider_eye:9000002
    cursor_pointer: fermented_spider_eye:9000003
    dyeing_pointer: fermented_spider_eye:9100003
    tutorial_gui: fermented_spider_eye:9100004
    tutorial_gui_checked: fermented_spider_eye:9100005
    slots:
      colors:
        not_owned: 195,147,57
        owned: 56,67,100
        wearing: 57,70,195
        wearing_preview: 195,120,57
        max_amount_reached: 111,111,111
      add_item_in_blank_slots:
        # This is useful only for some expert users that need to do some crazy stuff.
        # Do not enable it if you don't know what you are doing.
        enabled: false
        type: PAPER
        custom_model_data: 1337666
send_creative_hidden_hat_message: true
save:
  # Use only one at a time
  file:
    enabled: false
  mysql:
    enabled: true
    url: jdbc:mysql://127.0.0.1:3306
    username: root
    password: 
    table: cosmeticscore_saved
debug: false
```

**Comment by LoneDev6** [comment]
I found out that the game itself hides player nametag if any entity is riding the player.
I will provide a workaround for that.
