### ISSUE TITLE
Can't reload cosmetics as a console

### ISSUE THREAD

**Issue by EpicPlayerA10** [PluginBugs/Issues-CosmeticsCore#159]
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### Discord tag (optional)

epicplayera10

### What happened?

Can't reload cosmetics from console. When I send this command `/cosmeticsconfig cosmetics reload` in the console, then in the console it says `This command can be run only by players!`. I think it should be allowed to do this.

### Steps to reproduce the issue

1. Send command in the console `cosmeticsconfig cosmetics reload`

### Server version

This server is running Paper version git-Paper-172 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 72e87ab)

### CosmeticsCore Version

CosmeticsCore version 1.2.2f

### ProtocolLib Version

ProtocolLib version 5.1.0

### LoneLibs Version

LoneLibs version 1.0.25

**Comment by LoneDev6** [comment]
Thanks a lot! This will be checked as soon as possible
