### ISSUE TITLE
Customized color palette.

### ISSUE THREAD

**Issue by denkuper** [PluginBugs/Issues-CosmeticsCore#165]
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Describe the solution you'd like

Add a separate file where all the colors will be specified, and provide the ability to change them, for example:

Green:
1: #043fd03, 2: #4320d04, 3: #f656gb, ... 54: #4fdh55

Red:
1: #043fd03, 2: #4320d04, 3: #f656gb, ... 54: #4fdh55

### Is your feature request related to a problem?

No.

### Describe alternatives you've considered

No, sorry (/0/ _ \0\\).

### Additional context

There was a need to change defolt colors to improve personalization.

This will give more opportunities to people who create completely custom worlds with their own color scheme.

An example of how it might look in the game:

![Color](https://github.com/PluginBugs/Issues-CosmeticsCore/assets/132282048/47207c88-bbf2-40cf-bc89-72cf9a612a49)

I will be happy if you make this feature!!!

**Comment by LoneDev6** [comment]
This color picker is made exactly how an image editor color picker works which gives the player a lot of freedom to colorize their cosmetics.
Anyway making the requested change would require a rewrite of the system which I'd avoid since it would take much time and won't be used by a lot of people.

Note: the provided image is not clear.

Thanks
