### ISSUE TITLE
Skins Mechanic 

### ISSUE THREAD

**Issue by EspartaProJunior** [PluginBugs/Issues-CosmeticsCore#17]
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Describe the solution you'd like

Hi, I would like to add the option of skins, something like the same model but when you click on it, a menu opens where you can select several models (same model but different textures). 

### Is your feature request related to a problem?

no

### Describe alternatives you've considered

no

### Additional context

This would serve to make it more intuitive and expand how the cosmetics look, it would also be nice to add the option of lore to the cosmetics.

**Comment by LoneDev6** [comment]
Interesting idea, but this would require a restructure of the current cosmetics GUI.
For now it supports only 3 categories: hat, body, balloon.

I got some suggestions, so it would have these buttons:
hat, body, offhand, balloon, skin

But I don't know, seems too much stuff

**Comment by EspartaProJunior** [comment]
You could make it so that when you click on a cosmetic with skin another menu will appear with only the skins of that cosmetic.

**Comment by EspartaProJunior** [comment]
You could make it so that when you click on a cosmetic with skin another menu will appear with only the skins of that cosmetic.
