### ISSUE TITLE
Click event are not cancelling in wardrobe

### ISSUE THREAD

**Issue by Pattanawaris** [PluginBugs/Issues-CosmeticsCore#170]
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### What happened?

When player click to open wardrobe gui the click they perform still remain(ex. Item in player's hand that cast skill by clicking while holding them are casted unintentionally during wardrobe using.)

### Steps to reproduce the issue

hold some item that execute something by clicking while holding it and open gui in wardrobe by left clicking.

### Server version

Paper-108 (1.20.1)

### CosmeticsCore Version

1.2.2g

### ProtocolLib Version

5.1.0

### LoneLibs Version

1.0.27

**Comment by FrancescoJacovo** [comment]
probably it's the same problem that broke our Bedrock compatibilty :(

**Comment by FrancescoJacovo** [comment]
When they enter the wardrobe see for 1 second the wardrobe gui that will close instantly and never possible to re-open. For java players everything works fine.

**Comment by LoneDev6** [comment]
Is your skills plugin using the correct event listener priority? I do cancel my click events.

**Comment by Pattanawaris** [comment]
Im not sure about that, but its Mmoitems plugin. but I solved it by creating a wardrobe region to prevent skill casting for now.

**Comment by FrancescoJacovo** [comment]
We didn't added anything betweek cosmetics core and bedrock players while they're in wardrobe, did u changed something in the last versions? It broke with the 1.20 update

**Comment by FrancescoJacovo** [comment]
In some of our instance the player can also move around flying

**Comment by FrancescoJacovo** [comment]
Did u add a method to open specific menu in the API? We can make some workaround

**Comment by LoneDev6** [comment]
> We didn't added anything betweek cosmetics core and bedrock players while they're in wardrobe, did u changed something in the last versions? It broke with the 1.20 update

No I didn't change anything.
Just implemented 1.20+ support.

This is why I never support bedrock compatibility, because it's always unreliable and prone to breaking between updates.

**Comment by FrancescoJacovo** [comment]
Yeah i know! and for the API method?

**Comment by FrancescoJacovo** [comment]
Lone?

> > We didn't added anything betweek cosmetics core and bedrock players while they're in wardrobe, did u changed something in the last versions? It broke with the 1.20 update
> 
> No I didn't change anything. Just implemented 1.20+ support.
> 
> This is why I never support bedrock compatibility, because it's always unreliable and prone to breaking between updates.

**Comment by LoneDev6** [comment]
You should stop asking multiple feature requests / report multiple issues in the same issue page, open a separate one for each single request.
Anyway be more specific on what you want to do, what you'd expect to happen and what you need to be added to the API.
