### ISSUE TITLE
Optimization

### ISSUE THREAD

**Issue by Lerphie** [PluginBugs/Issues-CosmeticsCore#176]
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### Discord tag (optional)

Coder#6926

### What happened?

I have a large server with over 300 people playing on it. When the players accumulate, your plugin causes a heavy load on the server processor. 

https://spark.lucko.me/n0wU4PFcJ3

### Steps to reproduce the issue

*

### Server version

This server is running GuardSpigot 1.16.5 version git-Airplane-"e37fa86" (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

### CosmeticsCore Version

![image](https://github.com/PluginBugs/Issues-CosmeticsCore/assets/66962762/be2b4fe6-70f2-421e-baef-874ffc30b637)

### ProtocolLib Version

![image](https://github.com/PluginBugs/Issues-CosmeticsCore/assets/66962762/4ae10628-63e4-4523-a538-b5c935be7f46)

### LoneLibs Version

![image](https://github.com/PluginBugs/Issues-CosmeticsCore/assets/66962762/5910406e-fa47-4e61-b090-6e3c6fbd7663)

### Other files, you can drag and drop them here to upload. (optional)

https://spark.lucko.me/n0wU4PFcJ3

### Screenshots/Videos (you can drag and drop files or paste links)

https://spark.lucko.me/n0wU4PFcJ3

**Comment by Lerphie** [comment]
The load is higher

![image](https://github.com/PluginBugs/Issues-CosmeticsCore/assets/66962762/dbb4209b-89a7-458e-a9d5-e5d937f282df)

25ms for main thread tasks

![image](https://github.com/PluginBugs/Issues-CosmeticsCore/assets/66962762/fa2dbce4-4399-4080-bbc4-38596414888d)

35ms for parse packet and then forward into protocollib and then into plugins

**Comment by LoneDev6** [comment]
TPS is 20, it's not causing excessive CPU load.

![image](https://github.com/PluginBugs/Issues-CosmeticsCore/assets/27242001/c5e284a7-ddda-4c98-be97-7185f7d9364e)


The plugin is coded with performance in mind, and was tested extensively on a server with more than 200 players moving around with cosmetics.

Did you experience any slowdown or the only alarming detail was the timings report orange ms indicators?

Anyway tomorrow I'll do a detailed check to see if the function you reported can be further optimized.

**Comment by Lerphie** [comment]
> TPS is 20, it's not causing excessive CPU load.
> 
> ![image](https://user-images.githubusercontent.com/27242001/282292936-c5e284a7-ddda-4c98-be97-7185f7d9364e.png)
> 
> The plugin is coded with performance in mind, and was tested extensively on a server with more than 200 players moving around with cosmetics.
> 
> Did you experience any slowdown or the only alarming detail was the timings report orange ms indicators?
> 
> Anyway tomorrow I'll do a detailed check to see if the function you reported can be further optimized.

![image](https://github.com/PluginBugs/Issues-CosmeticsCore/assets/66962762/d6474d1a-f190-4384-a399-3826190c875a)
What does this have to do with tps? Your plugin is putting a lot of strain on my system. It happens only on spawning (when players get very close to each other). In addition, the server begins to lag very much within those chunks where there are many players

**Comment by LoneDev6** [comment]
> What does this have to do with tps?

Well, TPS is the main thing you have to check to see if a server is performant or not.

> the server begins to lag very much within those chunks where there are many players

Provide a timings report of when the lag occurs.

**Comment by Lerphie** [comment]
> > What does this have to do with tps?
> 
> Well, TPS is the main thing you have to check to see if a server is performant or not.
> 
> > the server begins to lag very much within those chunks where there are many players
> 
> Provide a timings report of when the lag occurs.

You're wrong. I'd like to send you a video of the proof. How can I do it privately so others can't see it?

**Comment by LoneDev6** [comment]
Make a "payment issue" private ticket on my forum https://forum.devs.beer/

**Comment by LoneDev6** [comment]
![image](https://github.com/PluginBugs/Issues-CosmeticsCore/assets/27242001/14d1c73e-d7fb-4c4d-ace5-d43493789bb6)

Update to DEV builds of Via
https://ci.viaversion.com/job/ViaVersion-DEV/
https://ci.viaversion.com/view/ViaBackwards/job/ViaBackwards-DEV/

I think the lag is caused by ViaVersion printing too many error messages.

**Comment by LoneDev6** [comment]
Anyway analyzing the timings report I found out that you have some plugin that is refreshing the player inventory a lot.
This causes the CosmeticsCore hat reskin code to be called a lot of times.
This code has a part which reskins the read helmet to have the custom helmet skin.

![image](https://github.com/PluginBugs/Issues-CosmeticsCore/assets/27242001/58c9a338-9fe1-4e12-8546-f719bbb4da13)

I will do some more tests to see if I can optimize it or I will add an option to skip part of this code.
The heavy part of this code is the lore and display name logic to make it italic, which might sound stupid but I am using the internal game code to do that, so it's a performance problem related to the code of the game itself.

**Comment by Lerphie** [comment]
> ![image](https://user-images.githubusercontent.com/27242001/282593216-14d1c73e-d7fb-4c4d-ace5-d43493789bb6.png)
> 
> Update to DEV builds of Via https://ci.viaversion.com/job/ViaVersion-DEV/ https://ci.viaversion.com/view/ViaBackwards/job/ViaBackwards-DEV/
> 
> I think the lag is caused by ViaVersion printing too many error messages.

Unfortunately it's not going to help me. This is a problem of ModelEngine 3 not being compatible with ViaVersion

https://github.com/ViaVersion/ViaVersion/issues/3522#issuecomment-1807129859

**Comment by Lerphie** [comment]
> Anyway analyzing the timings report I found out that you have some plugin that is refreshing the player inventory a lot. This causes the CosmeticsCore hat reskin code to be called a lot of times. This code has a part which reskins the read helmet to have the custom helmet skin.


Maybe the problem is in my plugin. Could you please check it?
[joinitems.zip](https://github.com/PluginBugs/Issues-CosmeticsCore/files/13342654/joinitems.zip)

**Comment by Lerphie** [comment]
or more likely it's the HuskSync plugin, it synchronizes the player's inventory (including what he's wearing on his head).

https://www.spigotmc.org/resources/husksync-1-16-1-20-sync-inventories-e-chests-x-server-advancements-map-art-stats-backups.97144/

**Comment by Lerphie** [comment]
I found a prioritized configuration, maybe it will help.
https://william278.net/docs/husksync/config-file
![image](https://github.com/PluginBugs/Issues-CosmeticsCore/assets/66962762/2ef7c91a-501d-4521-858c-10148da33728)

**Comment by Lerphie** [comment]
@LoneDev6 Did you fix it?

**Comment by LoneDev6** [comment]
> I will do some more tests to see if I can optimize it or I will add an option to skip part of this code.
The heavy part of this code is the lore and display name logic to make it italic, which might sound stupid but I am using the internal game code to do that, so it's a performance problem related to the code of the game itself.

I scheduled it to be fixed, please be patient, I will do my best to finish the upcoming update as soon as possible.
