### ISSUE TITLE
Teleporting out of wardrobe gives fly

### ISSUE THREAD

**Issue by Braynblocks** [PluginBugs/Issues-CosmeticsCore#189]
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### What happened?

Entering cosmetics area and teleporting to another world will give you fly.

### Steps to reproduce the issue

1. Just enter the wardrobe area.
2. Use any teleport command with the destination being in a different world.
3. Get the ability to fly.

### Server version

This server is running Pufferfish version git-Pufferfish-26 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 0020a8b on HEAD)

### CosmeticsCore Version

1.2.3

### ProtocolLib Version

5.1.1

### LoneLibs Version

1.0.27

**Comment by LoneDev6** [comment]
Will be checked as soon as possible

**Comment by LoneDev6** [comment]
Can't reproduce the issue.
Tested on 1.20.4.
The user flight status gets reset after the teleport.
Probably something else is interfering, like a worldguard rule or another plugin.
