### ISSUE TITLE
double player tags

### ISSUE THREAD

**Issue by Ecilpse** [PluginBugs/Issues-CosmeticsCore#190]
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### What happened?

![image](https://github.com/PluginBugs/Issues-CosmeticsCore/assets/25452835/a8ebccb7-912d-44e6-9098-3ecbe5b0b286)
If player wear backpack cosmetics,player will see two "player" name tags.
i use "TAB" plugin for player tags.

### Steps to reproduce the issue

This happened after updating from 1.2.2f version to 1.3.5-r5.

### Server version

purpur-2014 (1.20.1)

### CosmeticsCore Version

 1.3.5-r5.

### ProtocolLib Version

5.1.0

### LoneLibs Version

1.0.27

**Comment by SwartZCoding** [comment]
I confirm this bug on : 

1.20.1
Tab 3.1.8
Cosmeticscore 1.2.3-r5
Protocollib 5.1.0
LoneLib : 1.0.27

**Comment by Ecilpse** [comment]
> Disable that in config.yml of CosmeticsCore `fix_invisible_nametag: false`
> 
> In the next update I will set this to false if TAB is installed.

![2023-12-06_07 03 23](https://github.com/PluginBugs/Issues-CosmeticsCore/assets/25452835/5c9fee8a-17e2-4b43-9f25-131def840d2f)
when player equip enchanted helemt, helmet cosmetics also apply enchantments, is there anyways to fix it?
this problems also occurs after update.

**Comment by LoneDev6** [comment]
Please do not report multiple issues on the same issue report page.
No there is no fix for that currently. I opened a new issue report #191 to keep track of the issue, but this was caused by this fix: https://github.com/PluginBugs/Issues-CosmeticsCore/issues/176#issuecomment-1816689213
