### ISSUE TITLE
customize menu visual bug

### ISSUE THREAD

**Issue by Dr1yest** [PluginBugs/Issues-CosmeticsCore#193]
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### What happened?

When opening the customization menu with items in inventory, you can see them, which interferes with color selection. they are phantom, but still.
![Знімок екрана з 2023-12-09 02-02-13](https://github.com/PluginBugs/Issues-CosmeticsCore/assets/75623091/a610c4b2-aa2d-4a67-bb5e-73198f69fb85)

### Steps to reproduce the issue

open customization menu with items in inventory

### Server version

This server is running Purpur version git-Purpur-1171 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
Error obtaining version information
Previous version: git-Purpur-1613 (MC: 1.18.2)

### CosmeticsCore Version

CosmeticsCore version 1.2.3-r5

### ProtocolLib Version

ProtocolLib version 5.1.0

### LoneLibs Version

LoneLibs version 1.0.31

**Comment by LoneDev6** [comment]
Please try that without any other plugins installed, another plugin might be sending inventory packets in a way that it breaks the custom menu.

Please let me know, thanks
