### ISSUE TITLE
Checking for inventory synchronization plugins

### ISSUE THREAD

**Issue by Lerphie** [PluginBugs/Issues-CosmeticsCore#195]
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

mc_coder

### Describe the solution you'd like

I have a plugin on my server to sync player inventory (HuskSync plugin). The problem is that HuskSync and CosmeticsCore simultaneously change the player's inventory (his headgear). Is it possible to fix it? For example, make a check of this plugin.

### Is your feature request related to a problem?

*

### Describe alternatives you've considered

*

### Additional context

*

**Comment by Lerphie** [comment]
@LoneDev6

**Comment by LoneDev6** [comment]
>  The problem is that HuskSync and CosmeticsCore simultaneously change the player's inventory (his headgear)

It's packet based, the item is not really like shown, HuskSync will be able to put the real item in inventory without issues.
I'm not really sure what is the issue discussed here.
