### ISSUE TITLE
Can't exit from wardrobe on server 1.20.2 and latest devbuild of ProtocolLib

### ISSUE THREAD

**Issue by EpicPlayerA10** [PluginBugs/Issues-CosmeticsCore#198]
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### Discord tag (optional)

epicplayera10

### What happened?

I set up a Paper server on 1.20.2 with CosmeticsCore. When I entered to the wardrobe and I tried to exit it using shift key, then I can't. It does nothing.

I discovered that when I downgrade the ProtocolLib to dev build 673 then the problem disappears. The problem appear on the latest dev build of ProtocolLib.

### Steps to reproduce the issue

1. Setup a Paper server on 1.20.2
2. Install CosmeticsCore, latest devbuild of ProtocolLib and LoneLibs
3. Enter to the wardrobe
4. Try to exit it using shift key.
5. See that you can't

### Server version

This server is running Paper version git-Paper-318 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: 9271ee7)

### CosmeticsCore Version

CosmeticsCore version 1.2.3b

### ProtocolLib Version

ProtocolLib version 5.2.0-SNAPSHOT-679

### LoneLibs Version

LoneLibs version 1.0.42

**Comment by LoneDev6** [comment]
Are you 100% sure it's caused by the latest version of ProtocoLib or was it just a coincidence?

**Comment by EpicPlayerA10** [comment]
I think this bug occurs because of the fact that the latest dev build of ProtocolLib is <ins>only</ins> for 1.20.4 and not for 1.20.2. Downgrading ProtocolLib to version that it supports 1.20.2 works fine. I think I can close this issue now.

**Comment by LoneDev6** [comment]
Thanks, will be checked, I need to find what changed between these ProtocolLib builds.

**Comment by Kosoca** [comment]
I may have found the solution (for my part it works) You must ensure that the entrance to the wardrobe is not on the same path as the exit, otherwise the player will be directly teleported back

**Comment by LoneDev6** [comment]
Seems a bug of ProtocolLib `5.2.0-SNAPSHOT-679` and 1.20.2.
For some reason `PacketType.Play.Client.STEER_VEHICLE.getPacketClass()` returns `ServerboundPongPacket` instead of `PacketPlayInSteerVehicle`.
Opened a new report here: https://github.com/dmulloy2/ProtocolLib/issues/2818
