### ISSUE TITLE
The backpack is not painted

### ISSUE THREAD

**Issue by RaydenKonig** [PluginBugs/Issues-CosmeticsCore#2]
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://CosmeticsCore.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### What happened?

When testing the plugin, I realized that the backpack does not work the painting function, in the preview the color is fine, but once you go out and see yourself, you cannot see the color

I think maybe it has something to do with the "self" function

### Steps to reproduce the issue

enter the wardrobe and choose the paintable backpack, paint it and exit

### Server version

1.19.2

### CosmeticsCore Version

1.0.0

### ProtocolLib Version

5.0.0-SNAPSHOT-b588

### LoneLibs Version

1.0.20

### Screenshots/Videos (you can drag and drop files or paste links)

https://media.discordapp.net/attachments/1020576027702984704/1020576312693370941/Minecraft__1.19.2_-_Multijugador_servidor_de_terceros_2022-09-17_03-01-30.mp4

**Comment by LoneDev6** [comment]
Will be fixed, thanks
