### ISSUE TITLE
Cosmetic unsynchronization

### ISSUE THREAD

**Issue by Lerphie** [PluginBugs/Issues-CosmeticsCore#200]
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### Discord tag (optional)

mc_coder

### What happened?

After updating the CosmeticCore plugin, I found a problem with cosmetics not keeping up with the player. And the most interesting thing is that for each player the cosmetics are in different positions. To fix this I need to teleport to the spawn and back to the player for which the cosmetics do not have time to move.

https://youtu.be/gby_FzQSHn4

### Steps to reproduce the issue

*

### Server version

This server is running GuardSpigot 1.16.5 version git-Airplane-"16d5bbf" (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

### CosmeticsCore Version

![image](https://github.com/PluginBugs/Issues-CosmeticsCore/assets/66962762/255979cb-f971-405e-9195-3266ab3364b3)

### ProtocolLib Version

![image](https://github.com/PluginBugs/Issues-CosmeticsCore/assets/66962762/27796d25-63d1-4917-88a0-781c5496462d)

### LoneLibs Version

![image](https://github.com/PluginBugs/Issues-CosmeticsCore/assets/66962762/49427485-6872-4f8d-8ed0-b4a24af2bb3c)

### Screenshots/Videos (you can drag and drop files or paste links)

https://youtu.be/gby_FzQSHn4

**Comment by LoneDev6** [comment]
Will be tested, but might be related to another plugin editing the passengers of the player.
