### ISSUE TITLE
Nickname duplication

### ISSUE THREAD

**Issue by Lerphie** [PluginBugs/Issues-CosmeticsCore#201]
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### Discord tag (optional)

mc_coder

### What happened?

Hi, I found a bug related to backpacks/wings. If you put them on, the player's nickname is duplicated. This problem was not there before, it appeared after switching to the latest version of CosmeticsCore

https://youtu.be/CSKdtNZa39k

### Steps to reproduce the issue

*

### Server version

This server is running GuardSpigot 1.16.5 version git-Airplane-"e37fa86" (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

### CosmeticsCore Version

![image](https://github.com/PluginBugs/Issues-CosmeticsCore/assets/66962762/d08a421a-8ede-4547-b941-2978b7260098)

### ProtocolLib Version

![image](https://github.com/PluginBugs/Issues-CosmeticsCore/assets/66962762/bec8c539-ff99-4b70-ac56-041a15e83fdc)

### LoneLibs Version

![image](https://github.com/PluginBugs/Issues-CosmeticsCore/assets/66962762/13ba0001-50b2-47f3-adc6-066a17ef22b7)

### Screenshots/Videos (you can drag and drop files or paste links)

https://youtu.be/CSKdtNZa39k

**Comment by LoneDev6** [comment]
Disable `fix_invisible_nametag` in config.yml
