### ISSUE TITLE
Poor wardrobe display with Optifine

### ISSUE THREAD

**Issue by Taks1k** [PluginBugs/Issues-CosmeticsCore#202]
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### What happened?

I can see my legs when I'm in the wardrobe, without Optifine everything is fine
![image](https://github.com/PluginBugs/Issues-CosmeticsCore/assets/156545563/5a58988d-78b4-4dcd-8aac-94e0e73c915a)
![image](https://github.com/PluginBugs/Issues-CosmeticsCore/assets/156545563/6e254c80-6b2e-4323-afba-08e09dc482fb)

### Steps to reproduce the issue

-

### Server version

This server is running Paper version git-Paper-388 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: fc9ee65 on ver/1.18.2)
You are running the latest version

### CosmeticsCore Version

1.2.3-r5

### ProtocolLib Version

5.1.0

### LoneLibs Version

1.0.45

**Comment by Taks1k** [comment]
???

**Comment by LoneDev6** [comment]
I will do some checks but might be an optifine bug and I might not be able to fix that as I cannot reproduce it with a client without mods.

Also note: no one uses Optifine anymore.
More info: https://www.reddit.com/r/feedthebeast/comments/15iuump/people_why_do_you_hate_optifine/

**Comment by LoneDev6** [comment]
Added a new setting: `use_invisibility_potion: true` to fix that.
It should make Optifine forcefully hide the player since it has invisibility potion applied.
