### ISSUE TITLE
The location of the backpack cosmetics looks a higher in 1.20.4

### ISSUE THREAD

**Issue by Ecilpse** [PluginBugs/Issues-CosmeticsCore#203]
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### Discord tag (optional)

EclipseMC#oing1215

### What happened?

The location of the backpack cosmetics looks a higher in 1.20.4

### Steps to reproduce the issue

1. make backpack cosmetics
2. see other's backpack cosmetics in 1.20.1 client
3. see other's backpack cosmetics in 1.20.4 client

### Server version

1.20.2

### CosmeticsCore Version

1.2.3b

### ProtocolLib Version

5.1.1-SNAPSHOT-673

### LoneLibs Version

1.0.31

### Screenshots/Videos (you can drag and drop files or paste links)

1.20.1
![2024-01-17_23 41 51](https://github.com/PluginBugs/Issues-CosmeticsCore/assets/25452835/0d9a630d-9a85-44b1-a62b-6aaeadc61fac)

1.20.4
![2024-01-17_23 40 52](https://github.com/PluginBugs/Issues-CosmeticsCore/assets/25452835/c8144a81-ca59-4bac-9a6e-7a6083bc63da)

**Comment by LoneDev6** [comment]
https://cosmeticscore.devs.beer/adding-content/body-cosmetic/static-body-cosmetic

Example using this pack: https://mcmodels.net/model/little-penguin-weapons-tools-cosmetics-set/

# 1.20.4

## In wardrobe

![image](https://github.com/PluginBugs/Issues-CosmeticsCore/assets/27242001/02f3fa8f-575c-416b-a0b3-fae6a8b2dbb8)

## Self view

![image](https://github.com/PluginBugs/Issues-CosmeticsCore/assets/27242001/1854d60a-226d-47af-ad0f-ae4a6d9a1b6a)

## Viewed by another player

![image](https://github.com/PluginBugs/Issues-CosmeticsCore/assets/27242001/f35ccdef-ed76-4e9f-b656-407e08a938a0)
