### ISSUE TITLE
head cosmetics was disaapeared after damaged

### ISSUE THREAD

**Issue by Ecilpse** [PluginBugs/Issues-CosmeticsCore#204]
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### Discord tag (optional)

EclipseMC#oing1215

### What happened?

video : https://youtu.be/lAGLEqllG6c

### Steps to reproduce the issue

1. equip helemt & helmet cosmetics
2. damaged

### Server version

purpur 1.20.2 RO.1 

### CosmeticsCore Version

1.2.3-r5

### ProtocolLib Version

1.2.3-r5

### LoneLibs Version

1.0.45 / IA 3.6.3-beta-9

**Comment by LoneDev6** [comment]
https://github.com/PluginBugs/Issues-CosmeticsCore/assets/27242001/5bcfa423-d3c6-457d-b1cd-3b2aa61ba993
