### ISSUE TITLE
Cosmetics can be taken out of armour slots

### ISSUE THREAD

**Issue by kylemarham** [PluginBugs/Issues-CosmeticsCore#205]
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### Discord tag (optional)

OhSoGamer#0

### What happened?

When applying a head cosmetic, users can move it out of the head slot into their inventory 

### Steps to reproduce the issue

Add a head item in Wardrobe or through the command 

Move the head item from your head to your inventory 

### Server version

This server is running Paper version git-Paper-365 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 1281f4f)
You are 40 version(s) behind
Download the new version at: https://papermc.io/downloads/paper
Previous version: git-Paper-309 (MC: 1.20.2)

### CosmeticsCore Version

1.2.3b

### ProtocolLib Version

5.2.0-SNAPSHOT-679

### LoneLibs Version

1.0.45

### CosmeticsCore config.yml

```shell
lang: en
extract_default_assets: true
cosmetics:
  max_equippable:
    body: 3
    balloon: 2
  hide_during_combat:
    enabled: true
    combat_duration_ticks: 10000
  fix_invisible_nametag: true
  hide_in_vanish: true
  worlds:
  - '*'
wardrobe_room:
  camera:
    hide_actionbar_texts: true
    rotation:
      enabled: true
    zoom:
      enabled: true
      min: 2
    fade_effect: true
    location:
      world: world
      x: -10747.832
      y: 67
      z: -6746.299
      yaw: -150
      pitch: 30
  mannequin:
    location:
      world: world
      x: -10746.669
      y: 65
      z: -6748.682
      yaw: 0
      pitch: 0
  teleport_area:
    enter:
      world: world
      pos1:
        x: -10746
        y: 64
        z: -6745
      pos2:
        x: -10746
        y: 66
        z: -6744
    exit_location:
      world: world
      x: -10746
      y: 65
      z: -6742
      yaw: 0
      pitch: 0
  gui:
    cursor_default: fermented_spider_eye:9000001
    cursor_rotate: fermented_spider_eye:9000002
    cursor_pointer: fermented_spider_eye:9000003
    dyeing_pointer: fermented_spider_eye:9100003
    tutorial_gui: fermented_spider_eye:9100004
    tutorial_gui_checked: fermented_spider_eye:9100005
    slots:
      colors:
        not_owned: 195,147,57
        owned: 56,67,100
        wearing: 57,70,195
        wearing_preview: 195,120,57
        max_amount_reached: 111,111,111
      add_item_in_blank_slots:
        # This is useful only for some expert users that need to do some crazy stuff.
        # Do not enable it if you don't know what you are doing.
        enabled: false
        type: PAPER
        custom_model_data: 1337666
send_creative_hidden_hat_message: true
save:
  # Use only one at a time
  file:
    enabled: true
  mysql:
    enabled: false
    url: jdbc:mysql://my_url_database_69.com:3306/database_name
    username: username
    password: password
    table: cosmeticscore_saved
debug: false
```

### Problematic items yml configuration file (optional)

```shell
cosmetics:
  lunar_head:
    display_name: Lunar Head
    dye:
      enabled: false
    enabled: true
    model:
      gui: potion:1740000
      normal: potion:1740000
    type: HAT
```

**Comment by LoneDev6** [comment]
Please make a video, I can't manage to reproduce the issue.
