### ISSUE TITLE
1.16.5 - Lags when moving an item

### ISSUE THREAD

**Issue by Lerphie** [PluginBugs/Issues-CosmeticsCore#208]
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### Discord tag (optional)

Coder#6926

### What happened?

The server starts to lag horribly when moving an item.

I noticed that this happens only on the survival server (which I haven't restarted for 4 days), maybe the problem lies in this. His spark: https://spark.lucko.me/2ARRp1xLEn

There is no lag on the spavn server, for the reason that I restart it every 6 hours: https://spark.lucko.me/k76XY0ds54.

### Steps to reproduce the issue

*

### Server version

This server is running GuardSpigot 1.16.5 version git-Airplane-"16d5bbf" (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

### CosmeticsCore Version

![image](https://github.com/PluginBugs/Issues-CosmeticsCore/assets/66962762/1362c08e-b30d-4821-8590-fee0a8fe99f8)

### ProtocolLib Version

![image](https://github.com/PluginBugs/Issues-CosmeticsCore/assets/66962762/e78820d1-9474-47dc-b97b-0398d68f6c53)

### LoneLibs Version

![image](https://github.com/PluginBugs/Issues-CosmeticsCore/assets/66962762/09a9d3f8-7e44-499e-99c4-538798c09799)

**Comment by LoneDev6** [comment]
Same issue: #199
Will be fixed
