### ISSUE TITLE
Java 11 compatibility

### ISSUE THREAD

**Issue by NotKili** [PluginBugs/Issues-CosmeticsCore#216]
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

notkili

### Describe the solution you'd like

A version of this plugin compiled against Java11

### Is your feature request related to a problem?

We run our server on Java11, Java16 causes a lot of compatibility issues with other plugins and is therefore no option. Updating all other plugins is no option due to the sheer amount of work.

### Describe alternatives you've considered

Commissioning a new cosmetics plugin or updating all other plugins

**Comment by LoneDev6** [comment]
Post the error you're getting, a full log would be preferred
