### ISSUE TITLE
Backpack broken after world teleport

### ISSUE THREAD

**Issue by MelonCraftDE** [PluginBugs/Issues-CosmeticsCore#22]
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### Discord tag (optional)

Bornyyy#9630

### What happened?

After world teleport the backpack is gone/different and stuck at spawn.
provided a video of the issue.

(using CMI warp, but happens also by using "/mvtp worldname" with Multiverse-Core)

### Steps to reproduce the issue

1. equip backpack
2. use warp into another world
3. watch your backpack

### Server version

> version
[07:43:27 INFO]: Checking version, please wait...
[07:43:27 INFO]: This server is running Paper version git-Paper-153 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 63cb747)

### CosmeticsCore Version

> version CosmeticsCore
[07:44:37 INFO]: CosmeticsCore version 1.0.1-beta2

### ProtocolLib Version

> version ProtocolLib
[07:44:49 INFO]: ProtocolLib version 5.0.0-SNAPSHOT-b600

### LoneLibs Version

> version LoneLibs
[07:45:02 INFO]: LoneLibs version 1.0.21

### Screenshots/Videos (you can drag and drop files or paste links)

https://www.youtube.com/watch?v=4njqB0NHMr4

**Comment by LoneDev6** [comment]
I cannot reproduce the issue, I'll do some tests again today, thanks

**Comment by LoneDev6** [comment]
I created a private thread on Discord
