### ISSUE TITLE
water_worker enchantments was not worked when equip head cosmetics

### ISSUE THREAD

**Issue by Ecilpse** [PluginBugs/Issues-CosmeticsCore#221]
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### Discord tag (optional)

Eclipse

### What happened?

water_worker enchantments was not worked when equip head cosmetics.

### Steps to reproduce the issue

1. enchant 'water_worker' enchant on helemt
2. pick stone with pickaxe without cosmetics & with cosmetics

### Server version

1.20.2-RO.1

### CosmeticsCore Version

1.2.3d

### ProtocolLib Version

5.1.1-SNAPSHOT-673

### LoneLibs Version

1.0.31

### Screenshots/Videos (you can drag and drop files or paste links)

youtube : https://youtu.be/3e1TnTWwkZs

**Comment by LoneDev6** [comment]
Related to https://github.com/PluginBugs/Issues-CosmeticsCore/issues/191 and https://github.com/PluginBugs/Issues-CosmeticsCore/issues/156

**Comment by LoneDev6** [comment]
Will be checked again, strange since I tested it before release.

**Comment by Ecilpse** [comment]
> Will be checked again, strange since I tested it before release.

still not checked? i still wait reply a month
