### ISSUE TITLE
There is a problem when people hit each other.

### ISSUE THREAD

**Issue by rraabbii27** [PluginBugs/Issues-CosmeticsCore#224]
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### What happened?

When someone hit other people, the message (Failed to update secure chat state for ID: 'Received chat packet with missing or invalid signature.') appears on the console and server, and the chat is not displayed and you are expelled from the server. Or, the person with the symptoms must leave the server and enter to participate in the chat.

And I want cosmetics to keep showing even if people hit each other. So I modified the config and still can't see it. Plus, I can't see cosmetics again after 10000 ticks.

Sometimes this phenomenon happens right away, but sometimes it doesn't.
The reason I see this phenomenon as a problem with cosmetics core is that it happens after adding this plug-in.

### Steps to reproduce the issue

1. Hit another person.

### Server version

This server is running Paper version git-Paper-430 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 4939f87)
You are 66 version(s) behind
Download the new version at: https://papermc.io/downloads/paper
Previous version: git-Paper-423 (MC: 1.20.4)

### CosmeticsCore Version

1.2.3d

### ProtocolLib Version

5.2.0-SNAPSHOT-679

### LoneLibs Version

1.0.45

### Error (optional)

```shell
[01:04:30 WARN]: Failed to update secure chat state for ID: 'Received chat packet with missing or invalid signature.'
[01:04:30 INFO]: ID lost connection: Received chat packet with missing or invalid signature.
[01:04:30 INFO]: ID left the game
```

### CosmeticsCore config.yml

```shell
lang: en
extract_default_assets: true
cosmetics:
  max_equippable:
    body: 3
    balloon: 2
  hide_during_combat:
    enabled: false
    combat_duration_ticks: 10000
  fix_invisible_nametag: true
  hide_in_vanish: true
  worlds:
  - '*'
wardrobe_room:
  camera:
    hide_actionbar_texts: true
    use_invisibility_potion: false
    rotation:
      enabled: true
    zoom:
      enabled: true
      min: 2
    fade_effect: true
    location:
      world: world
      x: -87.30000001192093
      y: 4.922977876653732
      z: -66.30000001192093
      yaw: 135.16846
      pitch: 12.556421
  mannequin:
    location:
      world: world
      x: -89.43431367578967
      y: 3.0
      z: -68.57988664213642
      yaw: 2.3197021
      pitch: 2.407764
  teleport_area:
    enter:
      world: world
      pos1:
        x: -91.0
        y: 5.0
        z: -68.0
      pos2:
        x: -89.0
        y: 3.0
        z: -68.0
    exit_location:
      world: world
      x: -89.34626405016624
      y: 2.5
      z: -64.0022881421476
      yaw: -3.192047
      pitch: 18.408337
  gui:
    cursor_default: fermented_spider_eye:9000001
    cursor_rotate: fermented_spider_eye:9000002
    cursor_pointer: fermented_spider_eye:9000003
    dyeing_pointer: fermented_spider_eye:9100003
    tutorial_gui: fermented_spider_eye:9100004
    tutorial_gui_checked: fermented_spider_eye:9100005
    slots:
      colors:
        not_owned: 195,147,57
        owned: 56,67,100
        wearing: 57,70,195
        wearing_preview: 195,120,57
        max_amount_reached: 111,111,111
      add_item_in_blank_slots:
        # This is useful only for some expert users that need to do some crazy stuff.
        # Do not enable it if you don't know what you are doing.
        enabled: false
        type: PAPER
        custom_model_data: 1337666
send_creative_hidden_hat_message: true
save:
  # Use only one at a time
  file:
    enabled: true
  mysql:
    enabled: false
    url: jdbc:mysql://my_url_database_69.com:3306/database_name
    username: username
    password: password
    table: cosmeticscore_saved
debug: false
```

**Comment by LoneDev6** [comment]
> (Failed to update secure chat state for ID: 'Received chat packet with missing or invalid signature.') 

Can't reproduce

> And I want cosmetics to keep showing even if people hit each other. So I modified the config and still can't see it. 

Can't reproduce, you can disable the option by setting it to false.

```yml
  hide_during_combat:
    enabled: false
    combat_duration_ticks: 10000
```

> I can't see cosmetics again after 10000 ticks.

I can't reproduce this too, it appears back after.
Anyway I found a bug, for some reason I implemented the check in the wrong way so it lasts less than expected (milliseconds instead of ticks).
In the next update please set it to 600, which is 30 seconds.


> You are 66 version(s) behind

Make sure to update to the latest 1.20.4 build.
