### ISSUE TITLE
Make possible to use balloon-type without lead

### ISSUE THREAD

**Issue by jamydariels** [PluginBugs/Issues-CosmeticsCore#228]
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

megadose

### Describe the solution you'd like

I have made a beautiful helicopter that follows me everywhere but i think it would be amazing if it didn't had a lead ?
If you implement this feature, i would for sure design more flying things to follow you, since i find it amazing.

Here is a preview of how it looks now : https://imgur.com/a/a8gBwNH

I thought it could be cool to have a parameter in cosmetic config like show-lead: and probably not too hard to code ^^
Thanks for considering this suggestion :)

### Is your feature request related to a problem?

No, it's not. It works as balloon type should.

### Describe alternatives you've considered

I thought maybe it could be possible to move the lead position the nearest to the player but probably it wouldn't be so good since it's "balloon position related".

**Comment by LoneDev6** [comment]
In the next update all balloons won't have a lead if no `leash_pivot` bone exists.

**Comment by LoneDev6** [comment]
Example:
```yml
  star_kite:
    display_name: "Star Kite"
    type: BALLOON_ENTITY
    balloon:
      leash: false
```

**Comment by jamydariels** [comment]
Oh damn! I believed it was not. Thanks a lot for your time !
