### ISSUE TITLE
Backpacks messing up with chat bubbles

### ISSUE THREAD

**Issue by emcrald** [PluginBugs/Issues-CosmeticsCore#231]
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### What happened?

# Issue
Using this [chat bubbles](https://www.spigotmc.org/resources/better-chat-bubbles%EF%B8%8F%EF%B8%8F%EF%B8%8F-%E2%AD%90-1-19-4-1-20-6-%E2%9C%85-packet-based-%E2%9C%85-animated-%E2%9C%85.115811/) plugin i bought when talking for some reason the backpacks start becoming stuttery? 

I get this isn't a problem that cosmeticscore should fix but I just wanted to report it because I paid for both the chat bubbles plugin and cosmeticscore so I want to be able to use them both simultaneously 

### Server version

This server is running Paper version git-Paper-446 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 6ad63fb)

### CosmeticsCore Version

CosmeticsCore version 1.2.3c

### ProtocolLib Version

ProtocolLib version 5.2.0-SNAPSHOT-679

### LoneLibs Version

LoneLibs version 1.0.45

### Screenshots/Videos (you can drag and drop files or paste links)

# Video:
https://www.youtube.com/watch?v=VTnxvrMbMkM

**Comment by LoneDev6** [comment]
Update to 1.2.3d and let me know, you're using an old version

**Comment by emcrald** [comment]
> Update to 1.2.3d and let me know, you're using an old version

There still seems to be compatibility issues with latest ia - cc - lonelibs - protcool lib
