### ISSUE TITLE
Render ModelEngine Balloons

### ISSUE THREAD

**Issue by PanHaskins** [PluginBugs/Issues-CosmeticsCore#239]
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### Discord tag (optional)

panhaskins

### What happened?

Problem with balloon rendering. As you can see in the video, the balloon is really only displayed for a very short distance (a couple of blocks).

This happens when I have a server view-distance of 5 and a simulation distance of 4-6.

It's so weird, since modelengine shows the other models from mythicmobs etc correctly as it does in the video, only the balloons don't. Due to this, the modelengine may be lagging probably because it's somehow working badly with their API and it's throwing "invisible" errores and only Spark is catching it. But that may just be my guess.

### Steps to reproduce the issue

1. Add CosmeticsCore and MEG 4
2. Set view-distance to 5 and simulation-distance to 4
3. Log on and equipt any type MEG balloon

### Server version

git-Purpur-2176 (MC: 1.20.4)

### CosmeticsCore Version

CosmeticsCore 1.2.3d

### ProtocolLib Version

ProtocolLib 5.2.0-SNAPSHOT-679

### LoneLibs Version

LoneLibs 1.0.45

### FULL server log

Any errors

### Screenshots/Videos (you can drag and drop files or paste links)

https://github.com/PluginBugs/Issues-CosmeticsCore/assets/58113388/d009dd8a-20ee-4f35-8411-cc498fae03bd

![image](https://github.com/PluginBugs/Issues-CosmeticsCore/assets/58113388/c09000d8-b575-4c15-b153-3c03b2c92da6)

**Comment by LoneDev6** [comment]
This probably has to do with MEG api itself.
Anyway please provide your report URL and the MEG version.

**Comment by PanHaskins** [comment]
ModelEngine R4.0.6.1
and I'd rather send you a spark report privately.

**Comment by SrMonsterYT** [comment]
> ### Terms
> * [x]  I'm using the very latest version of CosmeticsCore and its dependencies.
> * [x]  I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same issue was already reported.
> * [x]  I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if a solution is already known.
> * [x]  I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.
> 
> ### Discord tag (optional)
> panhaskins
> 
> ### What happened?
> Problem with balloon rendering. As you can see in the video, the balloon is really only displayed for a very short distance (a couple of blocks).
> 
> This happens when I have a server view-distance of 5 and a simulation distance of 4-6.
> 
> It's so weird, since modelengine shows the other models from mythicmobs etc correctly as it does in the video, only the balloons don't. Due to this, the modelengine may be lagging probably because it's somehow working badly with their API and it's throwing "invisible" errores and only Spark is catching it. But that may just be my guess.
> 
> ### Steps to reproduce the issue
> 1. Add CosmeticsCore and MEG 4
> 2. Set view-distance to 5 and simulation-distance to 4
> 3. Log on and equipt any type MEG balloon
> 
> ### Server version
> git-Purpur-2176 (MC: 1.20.4)
> 
> ### CosmeticsCore Version
> CosmeticsCore 1.2.3d
> 
> ### ProtocolLib Version
> ProtocolLib 5.2.0-SNAPSHOT-679
> 
> ### LoneLibs Version
> LoneLibs 1.0.45
> 
> ### FULL server log
> Any errors
> 
> ### Error (optional)
> _No response_
> 
> ### CosmeticsCore config.yml
> _No response_
> 
> ### Problematic items yml configuration file (optional)
> _No response_
> 
> ### Other files, you can drag and drop them here to upload. (optional)
> _No response_
> 
> ### Screenshots/Videos (you can drag and drop files or paste links)
>  2024-06-14.18-20-10.mp4 
> ![image](https://private-user-images.githubusercontent.com/58113388/339844790-c09000d8-b575-4c15-b153-3c03b2c92da6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2MDIyNzAsIm5iZiI6MTcyMjYwMTk3MCwicGF0aCI6Ii81ODExMzM4OC8zMzk4NDQ3OTAtYzA5MDAwZDgtYjU3NS00YzE1LWIxNTMtM2MwM2IyYzkyZGE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAyVDEyMzI1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkNzcwMjc3NzE5ZDljNzA5YzA4OThkY2FhOTkxZDI3YjU1NzIyYWI0MWVlYzFkZmMzYWZkMWNhZjk2MzhkN2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Q1i6HS_zOR-2OD0Txy8OoUhJChi-7z-O7cTxW7LId5U)

same problem here: https://youtu.be/K2ATErblMak

server: git-Pufferfish-47 MC: 1.20.4
CosmeticsCore_1.3.0-release-1
ModelEngine-4.0.6.1
ProtocolLib 5.3.0-SNAPSHOT-699
LoneLibs 1.0.54

**Comment by LoneDev6** [comment]
@PanHaskins 
This is my code, anyway I think it's an issue of MEG not my plugin.

```java
        ModelBlueprint blueprint = ModelEngineAPI.getBlueprint(customEntityKey);
        megModel = ModelEngineAPI.createActiveModel(blueprint);

        fakeMegEntity = new Dummy();
        fakeMegEntity.setLocation(loc);
        megEntity = ModelEngineAPI.createModeledEntity(fakeMegEntity);

        if (megEntity == null)
        {
            Msg.error("Failed to spawn custom entity '" + customEntityKey + "'! megEntity is null.");
            return;
        }

        megEntity.addModel(megModel, false);
        megEntity.setBaseEntityVisible(false);
        fakeMegEntity.setRenderRadius(loc.getWorld().getViewDistance());
```
