### ISSUE TITLE
A bug where the name tag appears twice when wearing the body cosmetic.

### ISSUE THREAD

**Issue by dafsdfasde** [PluginBugs/Issues-CosmeticsCore#249]
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### What happened?

A bug where the name tag appears twice when wearing the body cosmetic.

### Steps to reproduce the issue

When there are two or more players on the server and the body cosmetic is worn, the name tag appears twice.

### Server version

[10:02:29 INFO]: This server is running Paper version git-Paper-196 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 773dd72)
You are running the latest version
Previous version: git-Purpur-2062 (MC: 1.20.1)

### CosmeticsCore Version

CosmeticsCore version 1.2.4-release-1

### ProtocolLib Version

[10:02:48 INFO]: ProtocolLib version 5.2.0-SNAPSHOT-679
[10:02:48 INFO]: Provides read/write access to the Minecraft protocol.
[10:02:48 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

[10:02:57 INFO]: LoneLibs version 1.0.54
[10:02:57 INFO]: Collection of libs used by my plugins
[10:02:57 INFO]: Authors: LoneDev and others

### Other files, you can drag and drop them here to upload. (optional)

https://github.com/PluginBugs/Issues-CosmeticsCore/assets/170809526/77206036-27d3-4ce0-ad83-807ac397f543

**Comment by dafsdfasde** [comment]
@LoneDev6 
The reason for seeing duplicate name tags is due to a conflict between the nametag functionality in either the VelocityTab plugin or the TAB plugin. Can you help resolve this issue?

**Comment by dafsdfasde** [comment]
> 중복된 이름 태그가 표시되는 이유는 VelocityTab 플러그인 또는 TAB 플러그인의 이름 태그 기능 간의 충돌 때문입니다. 이 문제를 해결하는 데 도움을 줄 수 있습니까?
If this feature is not implemented, you can test it by adding the TAB plugin or VelocityTab plugin to the proxy server.

**Comment by dafsdfasde** [comment]
> @LoneDev6 The reason for seeing duplicate name tags is due to a conflict between the nametag functionality in either the VelocityTab plugin or the TAB plugin. Can you help resolve this issue?

If this feature is not implemented, you can test it by adding the TAB plugin or VelocityTab plugin to the proxy server.

**Comment by LoneDev6** [comment]
Disable it in config.yml of CosmeticsCore. `fix_invisible_nametag: false`
