### ISSUE TITLE
Wings Height bugged, and no options to correct the Y pos of it

### ISSUE THREAD

**Issue by C4ptainFoxy** [PluginBugs/Issues-CosmeticsCore#253]
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### Discord tag (optional)

youronlyonefriendlyneighbor

### What happened?

I tried to add wings to Cosmetic Core Wardrobe but when set it the wing is too height from the body and there is no options to correct Y level

PS: I bought the plugin on Polymart and your discord verification system crashes when i try to verify...
https://polymart.org/user/3zekielzorr.12493
"Error verifying user: AxiosError: Request failed with status code 403"
![image](https://github.com/user-attachments/assets/5baca309-8cc7-4629-b1ee-21ef673066ea)
Same for your forum, someone stole my email to link his account to it, meaning i can't link my own email to chat on the forum and ask for  help...

### Steps to reproduce the issue

Add a wing
Set the wing
Notice that the wing is not on your back but floating over your head

### Server version

Server is running Paper version git-Paper-462 (MC: 1.20.4)

### CosmeticsCore Version

1.3.0-release-1

### ProtocolLib Version

5.2.0-SNAPSHOT-679

### LoneLibs Version

1.0.54

### Problematic items yml configuration file (optional)

```shell
dark_crystal_wings:
    enabled: true
    display_name: "Dark Crystal Wings"
    type: BODY_ITEM
    model:
      gui: elitecreatures:ifrit_animated-wings
      normal: elitecreatures:ifrit_animated-wings
    dye:
      enabled: false
```

### Screenshots/Videos (you can drag and drop files or paste links)

![image](https://github.com/user-attachments/assets/b15dae99-af7b-4ff1-824f-174093f06d0a)

**Comment by SrMonsterYT** [comment]
this isn't a problem with the plugin but a misconfiguration, you need to configure the wings correctly, download the cosmeticsCore addon from blockbench and fix it.
