### ISSUE TITLE
Camera Broken in Wardrobe

### ISSUE THREAD

**Issue by Sixsoul** [PluginBugs/Issues-CosmeticsCore#26]
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### What happened?

When entering the wardrobe, the camera faces to 0.0 yaw no matter how I set the camera.

### Steps to reproduce the issue

1. Set camera facing any yaw other than 0.0
2. Realize it just faces you to 0.0 anyway.

Video: https://streamable.com/djleim

### Server version

Paper(387) 1.18.2-R0.1-SNAPSHOT

### CosmeticsCore Version

1.0.1-beta2

### ProtocolLib Version

4.8.0

### LoneLibs Version

1.0.21

**Comment by LoneDev6** [comment]
Update to 1.0.1-beta3
