### ISSUE TITLE
Back Cosmetics Moved after updating plugins to newer version

### ISSUE THREAD

**Issue by Dondius** [PluginBugs/Issues-CosmeticsCore#263]
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### Discord tag (optional)

Dondius@dondius

### What happened?

So i updated my server from 1.19.2 where everything worked just fine and up to 1.21.1 and now all back cosmetics are placed way to high i will take a long time to fix then all i just need to know why high of the invisable armor stand moved?

### Steps to reproduce the issue

close server on 1.19.2
update server and all plugins to 1.21.1
startup server
error all back cosmetics moved up

### Server version

This server is running Paper version 1.21.1-57-master@b483da4 (2024-09-01T18:09:05Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)

### CosmeticsCore Version

1.3.0-release-2

### ProtocolLib Version

5.3.0-SNAPSHOT-726

### LoneLibs Version

1.0.58

**Comment by MashesB** [comment]
Has this been looked into or fixed? I'm having the exact same issue since I went from 1.19 to 1.20.4

**Comment by Dondius** [comment]
not as far as i have seen the last i checked we had to fix the hight our self

**Comment by MashesB** [comment]
where do you adjust or edit that? in the actual blockbench file? or somewhere else?

**Comment by Dondius** [comment]
yes in the blockbench file or jason file

**Comment by LoneDev6** [comment]
This is due to the fact that Mojang changed some entity ride height values in 1.20.2.
https://github.com/PluginBugs/Issues-CosmeticsCore/issues/168#issuecomment-1780917593
