### ISSUE TITLE
ModelEngine balloons

### ISSUE THREAD

**Issue by LoneDev6** [PluginBugs/Issues-CosmeticsCore#34]
### Describe the solution you'd like

A way to create balloons using the MEG entities instead of IA entities.

**Comment by morphin06** [comment]
Is there an ETA for this update?
More than a month now till now no  updates.
Hoping thanks

**Comment by Boy0000** [comment]
> Is there an ETA for this update? More than a month now till now no updates. Hoping thanks

![image](https://user-images.githubusercontent.com/62521371/199022415-20b67bcf-5cb9-40e7-aca6-67be3c4dd84a.png)

**Comment by morphin06** [comment]
As he said above it will add next update, 
Sad, It doesn't include a support from updates today.

**Comment by LoneDev6** [comment]
Implemented.
Please refer to the new wiki tutorials.
