### ISSUE TITLE
ItemsAdder HUDs showing in the wardrobe

### ISSUE THREAD

**Issue by LoneDev6** [PluginBugs/Issues-CosmeticsCore#37]
Add an option in config.yml to cancel ANY actionbar packet received by the client when they are in the wardrobe, or maybe somehow disable the ItemsAdder HUDs while in the wardrobe.

The second idea would be less performance heavy.

**Comment by dinobossytnew** [comment]
if I prefer to have more performance the truth because I use too many 3d models that consume a lot of memory obviously is not something very big but I prefer to keep the perfect performance as always.

**Comment by LoneDev6** [comment]
Notes:
This would require a new handy API method for ItemsAdder to forcefully disable huds rendering.
Right now there is no way to do that by using the API.
