### ISSUE TITLE
Name hiding when using body cosmetic

### ISSUE THREAD

**Issue by Senior-S** [PluginBugs/Issues-CosmeticsCore#38]
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### Discord tag (optional)

Senior S#2705

### What happened?

When a player is using body cosmetics (At least the default ones) the player name hide and aren't visible for other players.

### Steps to reproduce the issue

1. Set up a paper server with the CosmecticsCore plugin.
2. Wear a body cosmetic.
3. Your nametag will become invisible for everyone in the server.

### Server version

This server is running Paper version git-Paper-173 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: abe53a7)

### CosmeticsCore Version

CosmeticsCore version 1.0.2-beta

### ProtocolLib Version

ProtocolLib version 5.0.0-SNAPSHOT-b600

### LoneLibs Version

LoneLibs version 1.0.21

### FULL server log

[latest.log](https://github.com/PluginBugs/Issues-CosmeticsCore/files/9682309/latest.log)

### CosmeticsCore config.yml

```shell
lang: en
extract_default_assets: false
cosmetics:
  max_equippable:
    body: 3
    balloon: 2
wardrobe_room:
  camera:
    rotation:
      enabled: true
    zoom:
      enabled: true
      min: 2
    fade_effect: true
    location:
      world: world
      x: -2.5647227939174404
      y: 69.62000000476837
      z: 74.0149634901089
      yaw: 89.71823
      pitch: 9.434771
  mannequin:
    location:
      world: world
      x: -8.673565069429102
      y: 68.0
      z: 73.84777756663935
      yaw: -89.05707
      pitch: 5.389364
  teleport_area:
    enter:
      world: world
      pos1:
        x: 1.0
        y: 70.0
        z: 75.0
      pos2:
        x: 1.0
        y: 68.0
        z: 72.0
    exit_location:
      world: world
      x: 4.614983419625448
      y: 68.0
      z: 73.9530495913661
      yaw: -102.96797
      pitch: 23.895481
  gui:
    cursor_default: fermented_spider_eye:9000001
    cursor_rotate: fermented_spider_eye:9000002
    cursor_pointer: fermented_spider_eye:9000003
    dyeing_pointer: fermented_spider_eye:9100003
    tutorial_gui: fermented_spider_eye:9100004
    tutorial_gui_checked: fermented_spider_eye:9100005
    slots:
      colors:
        not_owned: 195,147,57
        owned: 56,67,100
        wearing: 57,70,195
        wearing_preview: 195,120,57
        max_amount_reached: 111,111,111
save:
  # Use only one at a time
  file:
    enabled: true
  mysql:
    enabled: false
    url: jdbc:mysql://my_url_database_69.com:3306/database_name
    username: username
    password: password
    table: cosmeticscore_saved
debug: false
```

### Screenshots/Videos (you can drag and drop files or paste links)

https://streamable.com/1q897e

**Comment by LoneDev6** [comment]
Try to remove TabList
