### ISSUE TITLE
Removing Manually a cosmetic duplicates the item

### ISSUE THREAD

**Issue by gabriel262m** [PluginBugs/Issues-CosmeticsCore#39]
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### Discord tag (optional)

GabrielC#8594

### What happened?

I tried to remove a hat cosmetic when equipped, it duplicates and can be placed on ground, im using paper 1.18.2
![prueba](https://user-images.githubusercontent.com/48396708/193304739-610720d3-12e6-4ba8-a859-87a749a5edf1.png)

### Steps to reproduce the issue

equip the hat
go outside wardrobe,  unequip like a normal item

### Server version

[10:30:21 INFO]: This server is running Paper version git-Paper-387 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: df630a2 on ver/1.18.2)
You are 1 version(s) behind
Download the new version at: https://papermc.io/downloads

### CosmeticsCore Version

CosmeticsCore version 1.0.2-beta

### ProtocolLib Version

[10:31:12 INFO]: ProtocolLib version 5.0.0-SNAPSHOT-b598
[10:31:12 INFO]: Provides read/write access to the Minecraft protocol.
[10:31:12 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

[10:31:31 INFO]: LoneLibs version 1.0.21
[10:31:31 INFO]: Collection of libs used by my plugins
[10:31:31 INFO]: Authors: LoneDev and others

### FULL server log

[latest.log](https://github.com/PluginBugs/Issues-CosmeticsCore/files/9685840/latest.log)

### CosmeticsCore config.yml

```shell
lang: en
extract_default_assets: true
cosmetics:
  max_equippable:
    body: 3
    balloon: 2
wardrobe_room:
  camera:
    rotation:
      enabled: true
    zoom:
      enabled: true
      min: 2
    fade_effect: true
    location:
      world: world
      x: -368.22132297233827
      y: 73.62000000476837
      z: -53.003804279083354
      yaw: -176.27281
      pitch: -1.3485522
  mannequin:
    location:
      world: world
      x: -368.20828962713887
      y: 72.0
      z: -57.82817554014952
      yaw: 0.72720337
      pitch: -8.848554
  teleport_area:
    enter:
      world: world
      pos1:
        x: -371.0
        y: 74.0
        z: -51.0
      pos2:
        x: -367.0
        y: 72.0
        z: -51.0
    exit_location:
      world: world
      x: -368.277005303772
      y: 72.0
      z: -48.2190599419198
      yaw: -176.42255
      pitch: 6.451481
  gui:
    cursor_default: fermented_spider_eye:9000001
    cursor_rotate: fermented_spider_eye:9000002
    cursor_pointer: fermented_spider_eye:9000003
    dyeing_pointer: fermented_spider_eye:9100003
    tutorial_gui: fermented_spider_eye:9100004
    tutorial_gui_checked: fermented_spider_eye:9100005
    slots:
      colors:
        not_owned: 195,147,57
        owned: 56,67,100
        wearing: 57,70,195
        wearing_preview: 195,120,57
        max_amount_reached: 111,111,111
save:
  # Use only one at a time
  file:
    enabled: true
  mysql:
    enabled: false
    url: jdbc:mysql://my_url_database_69.com:3306/database_name
    username: username
    password: password
    table: cosmeticscore_saved
debug: false
```

### Other files, you can drag and drop them here to upload. (optional)

  # Example hat item created with CustomModelData
  snow_fox_sleeping:
    display_name: "Snow Fox Sleeping"
    type: HAT
    model:
      gui: potion:400005
      normal: potion:400005
    dye:
      enabled: false

  # Example manually created hat with CustomModelData
  cowboy_hat:
    display_name: "Cowboy Hat"
    type: HAT
    model:
      gui: potion:300003
      normal: potion:300003
    dye:
      enabled: true

  # Example manually created hat with CustomModelData
  chef_hat:
    display_name: "Chef Hat"
    type: HAT
    model:
      gui: potion:400006
      normal: potion:400006
    dye:
      enabled: false
  
  # Example manually created hat with CustomModelData
  witch_hat:
    display_name: "Witch Hat"
    type: HAT
    model:
      gui: potion:400007
      normal: potion:400007
    dye:
      enabled: true

  squirrel_tail:
    display_name: "Squirrel Tail"
    type: BODY_ITEM
    model:
      gui: potion:400008
      normal: potion:400008
      self: potion:400009
    dye:
      enabled: false

  bee_nest:
    display_name: "Bee Nest"
    type: BODY_ITEM
    model:
      gui: potion:400010
      normal: potion:400010
      self: potion:400011
    dye:
      enabled: false

  backpack:
    display_name: "Backpack"
    type: BODY_ITEM
    model:
      gui: potion:400012
      normal: potion:400012
      self: potion:400013
    dye:
      enabled: false

  # Example custom body item created with ItemsAdder entities (supports also animated ItemsAdder entities models)
  wings_enderdragon:
    display_name: "Enderdragon Wings"
    type: BODY_ENTITY
    model:
      gui: dragon_head
      normal: cosmetics:wings_enderdragon
    dye:
      enabled: false
  
  # Example custom balloon created with ItemsAdder entities (supports also animated ItemsAdder entities models)
  amogus_balloon:
    display_name: "Amogus Balloon"
    type: BALLOON_ENTITY
    # Showing a different item into the GUI (in this case it's a must because ItemsAdder entities can't be put in GUIs)
    model:
      gui: potion:400014
      normal: cosmetics:amogus
    dye:
      enabled: true
      default: "#ff0000"

  # Example custom kite created with ItemsAdder entities (supports also animated ItemsAdder entities models)
  star_kite:
    display_name: "Star Kite"
    type: BALLOON_ENTITY
    # Showing a different item into the GUI (in this case it's a must because ItemsAdder entities can't be put in GUIs)
    model:
      gui: potion:400016
      normal: cosmetics:star_kite
    dye:
      enabled: true

  ballon_cluster:
    display_name: "Balloon Cluster"
    type: BALLOON_ENTITY
    model:
      gui: potion:400015
      normal: cosmetics:ballon_cluster
    dye:
      enabled: false

  locomotive:
    display_name: "Locomotive"
    type: BALLOON_ENTITY
    model:
      gui: potion:400017
      normal: cosmetics:locomotive
    dye:
      enabled: false

  # Example manually created hat with CustomModelData
  cat_ears_hat:
    display_name: "Orejas de Gato"
    type: HAT
    model:
      gui: carved_pumpkin:1
      normal: carved_pumpkin:1
    dye:
      enabled: false

  # Example manually created hat with CustomModelData
  pirate_hat:
    display_name: "Sombrero Pirata"
    type: HAT
    model:
      gui: carved_pumpkin:11
      normal: carved_pumpkin:11
    dye:
      enabled: false

**Comment by LoneDev6** [comment]
It's a known issue and has to do with creative mode.
This cannot be fixed.

I'm surprised you have added cosmetics while in creative since they are automatically deleted during gamemode change: https://github.com/PluginBugs/Issues-CosmeticsCore/issues/16
