### ISSUE TITLE
Wardrobe sometimes can't exit using shift

### ISSUE THREAD

**Issue by morphin06** [PluginBugs/Issues-CosmeticsCore#41]
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### Discord tag (optional)

Morphin#4404

### What happened?

Wardrobe sometimes can't exit using shift
No console error

### Steps to reproduce the issue

Entering wardrobe

### Server version

Paper 1.10.2

### CosmeticsCore Version

Latest

### ProtocolLib Version

Latest

### LoneLibs Version

Latest

**Comment by LoneDev6** [comment]
Can you make a video?
Anyway please provide valid versions, I see you skipped everything in the report info.
Also `Paper 1.10.2` has no sense

**Comment by morphin06** [comment]
That was 1.19.2
Its wrong typo. At least you should know that there isn't 1.10.2 yet.

**Comment by LoneDev6** [comment]
> Can you make a video?

Please provide also your client version

**Comment by morphin06** [comment]
[https://media.giphy.com/media/AMoFAWf7SeKoM4kPMU/giphy.gif](url)
In this gif i am pressing shift multiple times.

Vanilla client 1.19.2
With optifine

But when i restart a server its fine without any cosmetics equip to the player.
But when i wear a cosmetics after a couple a minutes and try to enter again.
You can't exit anymore using shift.

Cosmetics config, Default.
Full  server log
[https://mclo.gs/vOW1e74](url)

**Comment by LoneDev6** [comment]
Can you try with vanilla client?
Can you try to disable every other plugin?

This is the usual way to identify issues on ANY plugin, not only cosmeticscore.

**Comment by Kokolochnik** [comment]
> Can you try with vanilla client? Can you try to disable every other plugin?
> 
> This is the usual way to identify issues on ANY plugin, not only cosmeticscore.
> 
> Anyway a random log is not useful, you had to send a log of when the issue occurred.

same problem. vanilla client 1.19.2 and spigot core 1.18.2 just a few plugins - itemadder, cosmeticcore and all libraries

**Comment by Kokolochnik** [comment]
what core are you using on your test server?

**Comment by Kokolochnik** [comment]
![Снимок](https://user-images.githubusercontent.com/114332828/194317466-64942ef5-ca3f-4753-a629-e6a74f167734.PNG)

**Comment by LoneDev6** [comment]
@Kokolochnik do not post errors as image, post text.

**Comment by haroldrc** [comment]
same problem
