### ISSUE TITLE
Tail/backpack cosmetic shows while in spectator mode

### ISSUE THREAD

**Issue by Andre601** [PluginBugs/Issues-CosmeticsCore#43]
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### Discord tag (optional)

Andre_601#0601

### What happened?

When going into Spectator mode is the tail/backpack cosmetic still visible.

This happened to me with a cosmetic that doesn't have a `_self` variant set to use (Uses the normal one for self display)

### Steps to reproduce the issue

1. Add a body cosmetic
2. Switch into spectator mode

### Server version

[16:42:52 INFO]: This server is running Paper version git-Paper-196 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: ff67f1f)
You are running the latest version

### CosmeticsCore Version

[16:43:09 INFO]: CosmeticsCore version 1.0.2-beta

### ProtocolLib Version

[16:43:40 INFO]: ProtocolLib version 5.0.0-SNAPSHOT
[16:43:40 INFO]: Provides read/write access to the Minecraft protocol.
[16:43:40 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

[16:43:15 INFO]: LoneLibs version 1.0.21
[16:43:15 INFO]: Collection of libs used by my plugins
[16:43:15 INFO]: Authors: LoneDev and others

### CosmeticsCore config.yml

```shell
lang: en
extract_default_assets: true
cosmetics:
  max_equippable:
    body: 3
    balloon: 2
wardrobe_room:
  camera:
    rotation:
      enabled: true
    zoom:
      enabled: true
      min: 2
    fade_effect: true
    location:
      world: world
      x: 48.30000001192093
      y: 103.62000000476837
      z: 4.235917498745962
      yaw: -43.818542
      pitch: 0.29984158
  mannequin:
    location:
      world: world
      x: 52.49922393537348
      y: 102.0
      z: 8.419175865356726
      yaw: -179.8479
      pitch: -4.350211
  teleport_area:
    enter:
      world: world
      pos1:
        x: 53.0
        y: 123.0
        z: 5.0
      pos2:
        x: 51.0
        y: 120.0
        z: 5.0
    exit_location:
      world: world
      x: 52.472304288953104
      y: 120.0
      z: 4.303568219048989
      yaw: 179.8313
      pitch: -3.4500246
  gui:
    cursor_default: fermented_spider_eye:9000001
    cursor_rotate: fermented_spider_eye:9000002
    cursor_pointer: fermented_spider_eye:9000003
    dyeing_pointer: fermented_spider_eye:9100003
    tutorial_gui: fermented_spider_eye:9100004
    tutorial_gui_checked: fermented_spider_eye:9100005
    slots:
      colors:
        not_owned: 195,147,57
        owned: 56,67,100
        wearing: 57,70,195
        wearing_preview: 195,120,57
        max_amount_reached: 111,111,111
save:
  # Use only one at a time
  file:
    enabled: true
  mysql:
    enabled: false
    url: jdbc:mysql://my_url_database_69.com:3306/database_name
    username: username
    password: password
    table: cosmeticscore_saved
debug: false
```

### Problematic items yml configuration file (optional)

```shell
cosmetics:
  fox_ears:
    display_name: "Fox Ears"
    type: HAT
    model:
      gui: foxcosmetics:fox_ears
      normal: foxcosmetics:fox_ears
    dye:
      enabled: false
  snow_fox_ears:
    display_name: "Snow Fox Ears"
    type: HAT
    model:
      gui: foxcosmetics:snow_fox_ears
      normal: foxcosmetics:snow_fox_ears
    dye:
      enabled: false
  fox_tail:
    display_name: "Fox Tail"
    type: BODY_ITEM
    model:
      gui: foxcosmetics:fox_tail
      normal: foxcosmetics:fox_tail
    dye:
      enabled: false
  snow_fox_tail: # <-- This cosmetic is used
    display_name: "Snow Fox Tail"
    type: BODY_ITEM
    model:
      gui: foxcosmetics:snow_fox_tail
      normal: foxcosmetics:snow_fox_tail
    dye:
      enabled: false
```

### Screenshots/Videos (you can drag and drop files or paste links)

![issue](https://cdn.discordapp.com/attachments/689116299120476163/1027252638133256272/2022-10-05_17.59.43.png)

**Comment by Andre601** [comment]
Quickly sharing the plugins I'm using:
```
[16:46:01 INFO]: Plugins (27): AdvancedServerList, AdvancedTabOverlay, BKCommonLib, ChatChat, Citizens, CosmeticsCore, DecentHolograms, DeluxeMenus, Essentials, EssentialsDiscord, EssentialsSpawn, InteractiveBoard, ItemsAdder, LoneLibs, LuckPerms, Maplands, MobArena, Nova, PlaceholderAPI, PowerPlugins, ProtocolLib, QuickShop-Hikari, TCCoasters, Train_Carts, Vault, WorldEdit, WorldGuard
```

**Comment by LoneDev6** [comment]
Can't reproduce

```yml
  squirrel_tail_no_self:
    display_name: "Squirrel Tail NO SELF"
    type: BODY_ITEM
    model:
      gui: potion:400008
      normal: potion:400008
    dye:
      enabled: false
```


https://user-images.githubusercontent.com/27242001/195644198-df5a091d-f5ff-4ef2-887d-758a49706b34.mp4

**Comment by Andre601** [comment]
Maybe a WorldGuard thing?
I use WorldGuard on the server.

**Comment by LoneDev6** [comment]
Remove some plugins and test in order to find out the cause
