### ISSUE TITLE
Optifine bug - Player rendered while in wardrobe

### ISSUE THREAD

**Issue by TheSPREEGuy** [PluginBugs/Issues-CosmeticsCore#5]
### Discord tag (optional)

SPREEGuy#6969

### What happened?

when you go into the wardrobe it seems the player stays rendered with optifine.
i tried it with out optifine it works fine

### Steps to reproduce the issue

1. install optifine
2. then goto the wardrobe

### Server version

This server is running Paper version git-Paper-145 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 36f0c1b)

### CosmeticsCore Version

CosmeticsCore version 1.0.0-beta1

### ProtocolLib Version

ProtocolLib version 5.0.0-SNAPSHOT-b600

### LoneLibs Version

LoneLibs version 1.0.21

### CosmeticsCore config.yml

```shell
lang: en
cosmetics:
  max_equippable:
    hat: 1
    body: 3
    balloon: 2
wardrobe_room:
  camera:
    rotation:
      enabled: true
    zoom:
      enabled: true
      min: 2
    fade_effect: true
    location:
      world: world
      x: -11.594355342421863
      y: 74.90830710701725
      z: 66.42928261968228
      yaw: -44.84735
      pitch: 5.8498187
  mannequin:
    location:
      world: world
      x: -6.536689911909205
      y: 73.0
      z: 71.37894077077858
      yaw: 136.20312
      pitch: -5.400188
  teleport_area:
    enter:
      world: world
      pos1:
        x: -30.0
        y: 71.0
        z: 62.0
      pos2:
        x: -30.0
        y: 69.0
        z: 64.0
    exit_location:
      world: world
      x: -32.70704541066857
      y: 69.0
      z: 63.82080993097607
      yaw: -92.54498
      pitch: 4.649796
  gui:
    cursor_default: fermented_spider_eye:9000001
    cursor_rotate: fermented_spider_eye:9000002
    cursor_pointer: fermented_spider_eye:9000003
    dyeing_pointer: fermented_spider_eye:9100003
    tutorial_gui: fermented_spider_eye:9100004
    tutorial_gui_checked: fermented_spider_eye:9100005
    slots:
      colors:
        not_owned: 195,147,57
        owned: 56,67,100
        wearing: 57,70,195
        wearing_preview: 195,120,57
        max_amount_reached: 111,111,111
save:
  # Use only one at a time
  file:
    enabled: true
  mysql:
    enabled: false
    url: jdbc:mysql://my_url_database_69.com:3306/database_name
    username: username
    password: password
    table: cosmeticscore_saved
debug: false
```

### Screenshots/Videos (you can drag and drop files or paste links)

![image](https://user-images.githubusercontent.com/23518058/190865151-c346dec9-fd12-4bd8-be57-570e7294c552.png)

**Comment by MelonCraftDE** [comment]
have this issue too, but lonedev just closed my report. and its NOT an optifine bug, other wardrobes doesnt have the problem. sad reaction to just close it.

**Comment by LoneDev6** [comment]
> have this issue too, but lonedev just closed my report. and its NOT an optifine bug, other wardrobes doesnt have the problem. sad reaction to just close it.

Please when you report bugs open 1 github report per-bug not a single report with multiple bug reports.
That's why it was closed.

**Comment by LoneDev6** [comment]
@TheSPREEGuy will be checked tomorrow, thanks

**Comment by MelonCraftDE** [comment]
> > have this issue too, but lonedev just closed my report. and its NOT an optifine bug, other wardrobes doesnt have the problem. sad reaction to just close it.
> 
> Please when you report bugs open 1 github report per-bug not a single report with multiple bug reports. That's why it was closed.

then clarify it why you closed it. also i edited the report to a single report, hours ago before you closed it, which is clearly visible. so thats not within reason. but nevermind.
