### ISSUE TITLE
location not loaded if world is loaded after the plugin, in some cases

### ISSUE THREAD

**Issue by ItsSniper** [PluginBugs/Issues-CosmeticsCore#53]
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### Discord tag (optional)

Sniper#0001

### What happened?

Every time my server reboots, my players can no longer enter the wardrobe area. They get a message about an error in the config.yml. When I run the config reload command though, it all works perfectly fine. I’ve even regenerated the config and set the locations again and still seem to experience the issue. 

### Steps to reproduce the issue

Set up a wardrobe location on the latest paper 1.19.2 build. 
Reboot the server
Try to enter the wardrobe location
Reload the plugin’s config and it should work suddenly

### Server version

git-Paper-235 (MC 1.19.2)

### CosmeticsCore Version

1.0.3

### ProtocolLib Version

5.0.0-SNAPSHOT-b600

### LoneLibs Version

1.0.21

**Comment by LoneDev6** [comment]
> They get a message about an error

provide the error

**Comment by ItsSniper** [comment]
![C8897AB4-6127-4D83-90F3-0D05BFB30479](https://user-images.githubusercontent.com/33010572/197528058-b9f7b7fd-14cc-4e2c-9968-fed188878fa0.jpeg)

**Comment by LoneDev6** [comment]
Probably the world is not loaded in time.
I will add compatibility for this particular case.
