### ISSUE TITLE
Add 'face: <direction>' option to manequin-location

### ISSUE THREAD

**Issue by patatoplugin** [PluginBugs/Issues-CosmeticsCore#55]
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Describe the solution you'd like

Everytime I enter the wardrobe, the manequin always show his back to me
I tried to set manequin-location and find I can't change his orientation

### Is your feature request related to a problem?

NO

### Describe alternatives you've considered

add a setting to direction,
for example face: south mean the manequin look south

**Comment by LoneDev6** [comment]
Provide your server version.

Tested on 1.19.2: the mannequin rotation is correctly set based on the command.
`/cosmeticscore:cosmeticsconfig config set mannequin-location`
