### ISSUE TITLE
allows player to change the appearence of orignal armor without affecting its functionality

### ISSUE THREAD

**Issue by SnUncle** [PluginBugs/Issues-CosmeticsCore#56]
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

Sn#7574

### Describe the solution you'd like

I really like this plugin, but apparently it has a problem, which is that I can't go pvp while wearing costmetic stuff, because my helmet will be replaced directly. 

I would like to ask - is it possible to add a function that makes the costmetic only show without replacing any armor? that would be lit for every pvp-like server 

### Is your feature request related to a problem?

Yes, you cant pvp while have costmetic on

### Describe alternatives you've considered

add a option to only show costmetic items without replacing armors

**Comment by LoneDev6** [comment]
Custom cosmetic armors are not planned because there is no way to create custom armors models.
