### ISSUE TITLE
Potions can't be loaded

### ISSUE THREAD

**Issue by raksodnus** [PluginBugs/Issues-CosmeticsCore#58]
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### Discord tag (optional)

raksodnus__#7774

### What happened?

https://www.klgrth.io/paste/ryrku

### Steps to reproduce the issue

1. install and setup items adder and requitments (protocollibs, lonelibs, protocollibs etc.)

2. install cosmetics core - setup wardrope

3. copy assets and example cosmetics and paste cosmetics /plugins/cosmeticscore/cosmetics folder & assets minecraft/assets/items/potions :)

4. get this eror :)

### Server version

1.18.2

### CosmeticsCore Version

1.0.3

### ProtocolLib Version

4.8.0

### LoneLibs Version

1.0.21

### FULL server log

There was an error creating your Issue: body is too long (maximum is 65536 characters).

github eror :) my console is here:
https://www.klgrth.io/paste/oxmys

### Error (optional)

```shell
https://www.klgrth.io/paste/8yez9
```

### CosmeticsCore config.yml

```shell
https://www.klgrth.io/paste/86fox
```

**Comment by LoneDev6** [comment]
Please fix the numerous errors from ItemsAdder and the `Error: please check the config.yml file and make sure locations are correct.` error before opening an issue report.
