### ISSUE TITLE
Zoom not working correctly when camera has custom pitch

### ISSUE THREAD

**Issue by Lerphie** [PluginBugs/Issues-CosmeticsCore#59]
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### Discord tag (optional)

Coder#6926

### What happened?
Turning the dummy is a bug
https://youtu.be/GTRaTxDrggQ

### Steps to reproduce the issue

Fix

### Server version

Current: git-Purpur-1832 (MC: 1.19.2)*
Previous: git-Purpur-1819 (MC: 1.19.2)
2 version(s) behind

### CosmeticsCore Version

1.0.3

### ProtocolLib Version

5.0.0-SNAPSHOT-b602

### LoneLibs Version

1.0.21

### FULL server log

He's not needed here. There are no errors there

### Error (optional)

```shell
He's not needed here. There are no errors there
```

### CosmeticsCore config.yml

```shell
lang: en
extract_default_assets: true
cosmetics:
  max_equippable:
    body: 3
    balloon: 2
wardrobe_room:
  camera:
    rotation:
      enabled: true
    zoom:
      enabled: true
      min: 2
    fade_effect: true
    location:
      world: spawn
      x: 14.699999988079071
      y: 65.18250000476837
      z: 8.699999988079071
      yaw: 135.14308
      pitch: 8.762878
  mannequin:
    location:
      world: spawn
      x: 9.511846252691772
      y: 62.5
      z: 3.588583506267767
      yaw: -46.16571
      pitch: -5.427885
  teleport_area:
    enter:
      world: spawn
      pos1:
        x: 9.0
        y: 60.0
        z: 9.0
      pos2:
        x: 9.0
        y: 63.0
        z: 15.0
    exit_location:
      world: spawn
      x: 5.622869995949744
      y: 59.0
      z: 11.512182908853926
      yaw: 155.90103
      pitch: -11.438085
  gui:
    cursor_default: fermented_spider_eye:9000001
    cursor_rotate: fermented_spider_eye:9000002
    cursor_pointer: fermented_spider_eye:9000003
    dyeing_pointer: fermented_spider_eye:9100003
    tutorial_gui: fermented_spider_eye:9100004
    tutorial_gui_checked: fermented_spider_eye:9100005
    slots:
      colors:
        not_owned: 195,147,57
        owned: 56,67,100
        wearing: 57,70,195
        wearing_preview: 195,120,57
        max_amount_reached: 111,111,111
save:
  # Use only one at a time
  file:
    enabled: true
  mysql:
    enabled: false
    url: jdbc:mysql://my_url_database_69.com:3306/database_name
    username: username
    password: password
    table: cosmeticscore_saved
debug: false
```

### Screenshots/Videos (you can drag and drop files or paste links)

https://youtu.be/GTRaTxDrggQ

**Comment by Lerphie** [comment]
@LoneDev6  Sorry about the ping. But you answer for a very long time, and I bought the plugin recently and have already noticed a serious bug

**Comment by Lerphie** [comment]
Please take this as a priority. The players are suffering.

**Comment by raksodnus** [comment]
bro you have a error like ? 

[19:27:51] [Server thread/WARN]: Unknown gui item: potion:300003
[19:27:51] [Server thread/WARN]: Unknown item: potion:300003

**Comment by LoneDev6** [comment]
Next time provide more information, this issue is vague

**Comment by Lerphie** [comment]
> 
I also noticed that the translation of "Left click" does not work. For example, I'm trying to translate this into Russian. The plugin writes "null" instead
