### ISSUE TITLE
Wardrobe NPC displays name and belowname

### ISSUE THREAD

**Issue by RebelDs** [PluginBugs/Issues-CosmeticsCore#60]
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### What happened?

The Wardrobe NPC has a name and a belowname objective (health), which I have no idea on how to remove.

### Steps to reproduce the issue

1. Set up plugin
2. Enter Wardrobe

### Server version

[16:45:28 INFO]: This server is running Paper version git-Paper-411 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 6625db3 on ver/1.17.1)
You are running the latest version
Previous version: git-Paper-794 (MC: 1.16.5)

### CosmeticsCore Version

[16:45:54 INFO]: CosmeticsCore version 1.0.3

### ProtocolLib Version

[16:46:07 INFO]: ProtocolLib version 4.8.0
[16:46:07 INFO]: Provides read/write access to the Minecraft protocol.
[16:46:07 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

[16:46:18 INFO]: LoneLibs version 1.0.21
[16:46:18 INFO]: Collection of libs used by my plugins
[16:46:18 INFO]: Authors: LoneDev and others

### FULL server log

Not necessary, no errors at all.

### CosmeticsCore config.yml

```shell
lang: en
extract_default_assets: true
cosmetics:
  max_equippable:
    body: 3
    balloon: 2
wardrobe_room:
  camera:
    rotation:
      enabled: true
    zoom:
      enabled: true
      min: 2
    fade_effect: true
    location:
      world: piratelobby
      x: -88.03209719600137
      y: 67.62000000476837
      z: -109.44584566715925
      yaw: -132.60126
      pitch: 25.800032
  mannequin:
    location:
      world: piratelobby
      x: -83.77454988506258
      y: 63.0625
      z: -113.40818956066754
      yaw: 48.899048
      pitch: -16.500036
  teleport_area:
    enter:
      world: piratelobby
      pos1:
        x: -2.0
        y: 68.0
        z: -17.0
      pos2:
        x: 2.0
        y: 64.0
        z: -17.0
    exit_location:
      world: piratelobby
      x: 0.22293154308743274
      y: 65.0
      z: 0.693184307864791
      yaw: 0.44921875
      pitch: -4.9500055
  gui:
    cursor_default: fermented_spider_eye:9000001
    cursor_rotate: fermented_spider_eye:9000002
    cursor_pointer: fermented_spider_eye:9000003
    dyeing_pointer: fermented_spider_eye:9100003
    tutorial_gui: fermented_spider_eye:9100004
    tutorial_gui_checked: fermented_spider_eye:9100005
    slots:
      colors:
        not_owned: 195,147,57
        owned: 56,67,100
        wearing: 57,70,195
        wearing_preview: 195,120,57
        max_amount_reached: 111,111,111
save:
  file:
    enabled: true
  mysql:
    enabled: false
    url: jdbc:mysql://my_url_database_69.com:3306/database_name
    username: username
    password: password
    table: cosmeticscore_saved
debug: false
```

### Screenshots/Videos (you can drag and drop files or paste links)

https://youtu.be/_6qNbbzPwHs

**Comment by LoneDev6** [comment]
It's probably caused by TAB plugin or similar.
