### ISSUE TITLE
Hats disappears completely when doing emotes, and doesn't come back as normal like other cosmetics. 

### ISSUE THREAD

**Issue by FreddieDK** [PluginBugs/Issues-CosmeticsCore#63]
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### Discord tag (optional)

Freddie#1234

### What happened?

When doing /emote command. Everything will disappear (as stated in docs) and everything comes back when you cancel the emote. Except hats..? (see the gif) - This is super annoying, as the players will ask why they loose their hats completely.

gif: https://imgur.com/a/cquVmOQ

### Steps to reproduce the issue

gif: https://imgur.com/a/cquVmOQ

### CosmeticsCore Version

CosmeticsCore version 1.0.5

### ProtocolLib Version

ProtocolLib version 5.0.0-SNAPSHOT-b602

### LoneLibs Version

LoneLibs version 1.0.21

### Screenshots/Videos (you can drag and drop files or paste links)

https://imgur.com/a/cquVmOQ

**Comment by LoneDev6** [comment]
Will be fixed
