### ISSUE TITLE
Wrong api method

### ISSUE THREAD

**Issue by sidey383** [PluginBugs/Issues-CosmeticsCore#64]
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### What happened?

dev.lone.cosmeticscore.api.temporary.CosmeticAccessor#isHolderEntityValid()
true only while entity null or nor valide
```  
public boolean isHolderEntityValid() {
    Entity entity = this.holderEntity.get();
    return (entity == null || !entity.isValid());
  }
```

### Steps to reproduce the issue

```
        List<CosmeticAccessor> cosmeticAccessors = (List<CosmeticAccessor> ) api.getEquippedCosmeticsAccessors(player);
        cosmeticAccessors.forEach(a -> System.out.println(a.getDisplayName() +" " + a.isHolderEntityValid() + " "+ a.isEquipped()));
        cosmeticAccessors = cosmeticAccessors.stream().filter(CosmeticAccessor::isEquipped).filter(CosmeticAccessor::isHolderEntityValid).toList();
        cosmetics.put(player, cosmeticAccessors);
        cosmeticAccessors.forEach(CosmeticAccessor::unequip);
```

### Server version

verstion 1.19.2

### CosmeticsCore Version

version 1.0.5

### ProtocolLib Version

version 5.0.0-SNAPSHOT-b602

### LoneLibs Version

verstion 1.0.21

### FULL server log

[21:30:42 INFO]: [GunGaleEmotes] Snow Fox Sleeping false true
[21:30:42 INFO]: [GunGaleEmotes] Squirrel Tail false true

**Comment by Lerphie** [comment]
@LoneDev6 I support him, it really needs to be done as soon as possible.

**Comment by Lerphie** [comment]
The author of this post is my friend. I looked at the last post and realized that someone had already written about it https://github.com/PluginBugs/Issues-CosmeticsCore/issues/63

**Comment by VerklicktTV** [comment]
I have the same problem in my plugins

**Comment by LoneDev6** [comment]
> The author of this post is my friend. I looked at the last post and realized that someone had already written about it #63

How has #64 to do with #63?

**Comment by LoneDev6** [comment]
Anyway this will be fixed.
