### ISSUE TITLE
Accuracy.

### ISSUE THREAD

**Issue by dinobossytnew** [PluginBugs/Issues-CosmeticsCore#65]
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### Discord tag (optional)

DinoBoss#6985

### What happened?

Well clearly there is a precision bug on how the door is selected so that a user can choose cosmetics when I enter this area of the door does not put me in cosmetic mode also I saw that when I try to enter from the side or above if I let this is curious because it should not happen should improve the vectors and coordinates of the doors selecio

### Steps to reproduce the issue

First place the cosmetic zone, look at the door, select it and you will see that the top and the sides of the door are also selected.

### Server version

1.19.2 petal

### CosmeticsCore Version

CosmeticsCore 1.0.5

### ProtocolLib Version

 version 5.0.0-SNAPSHOT-b602

### LoneLibs Version

lonelibs 1.0.21

### FULL server log

https://hastebin.com/fisanewamu.makefile

### CosmeticsCore config.yml

```shell
lang: en
extract_default_assets: true
cosmetics:
  max_equippable:
    body: 3
    balloon: 2
wardrobe_room:
  camera:
    rotation:
      enabled: true
    zoom:
      enabled: true
      min: 2
    fade_effect: true
    location:
      world: flat
      x: 205
      y: -58.5
      z: 41
      yaw: 359.85
      pitch: 6.6
    hide_actionbar_texts: true
  mannequin:
    location:
      world: flat
      x: 204.5
      y: -60
      z: 45.5
      yaw: 180
      pitch: 0
  teleport_area:
    enter:
      world: flat
      pos1:
        x: 167
        y: -61
        z: 42
      pos2:
        x: 167
        y: -57
        z: 37
    exit_location:
      world: flat
      x: 164
      y: -60
      z: 40
      yaw: 98
      pitch: 10
  gui:
    cursor_default: fermented_spider_eye:9000001
    cursor_rotate: fermented_spider_eye:9000002
    cursor_pointer: fermented_spider_eye:9000003
    dyeing_pointer: fermented_spider_eye:9100003
    tutorial_gui: fermented_spider_eye:9100004
    tutorial_gui_checked: fermented_spider_eye:9100005
    slots:
      colors:
        not_owned: 195,147,57
        owned: 56,67,100
        wearing: 57,70,195
        wearing_preview: 195,120,57
        max_amount_reached: 111,111,111
save:
  # Use only one at a time
  file:
    enabled: true
  mysql:
    enabled: false
    url: jdbc:mysql://my_url_database_69.com:3306/database_name
    username: username
    password: password
    table: cosmeticscore_saved
debug: false
```

### Problematic items yml configuration file (optional)

```shell
null
```

### Other files, you can drag and drop them here to upload. (optional)

null

### Screenshots/Videos (you can drag and drop files or paste links)

null

**Comment by Lerphie** [comment]
You have a custom server core. Remove Petal and put Purpur

**Comment by dinobossytnew** [comment]
> 

petal is better than purpur =)  [check](https://github.com/Bloom-host/Petal)

**Comment by dinobossytnew** [comment]
one plugin also blocks the other.

**Comment by dinobossytnew** [comment]
https://mclo.gs/xYg5JAy  1

**Comment by Lerphie** [comment]
> purpur or petal is the same the only thing that petal has better performance, try purpur as you said bro look at the result.

petal - has a bunch of holes and incompatibility issues. As soon as you create a server with a large online, you will understand this. By the way, if you choose between Petal and Maria. Then I will choose the second one, Maria has better performance than Petal

**Comment by dinobossytnew** [comment]
> https://github.com/etil2jz/Mirai

ok, This does not answer the problem that I still have even though I use purpur. 
I used purpur and the same thing keeps happening and it is no longer a lone problem.

**Comment by dinobossytnew** [comment]
Even with spigot it doesn't load me.

**Comment by dinobossytnew** [comment]
I discovered that mythicmobs interferes if I remove it the 2 plugins work and it does not cause failure but if I have them if it causes failure.

**Comment by LoneDev6** [comment]
I don't see how this is an issue, you're supposed to select a door and enter it.
Make a video to better explain the issue since I don't understand what you mean.
