### ISSUE TITLE
Players who lose permission while wearing cosmetics lose everything

### ISSUE THREAD

**Issue by JuanDouCore** [PluginBugs/Issues-CosmeticsCore#66]
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### What happened?

My players when losing cosmetic permissions (for example a user is vip and that rank has cosmetic permissions, but then user rank is placed, which does not have cosmetic permission) if this happens while he is using cosmetics, the server throws him out and upon entering the player loses everything they had in their inventory and their food is completely lowered. This only happens with cosmeticoscore I already proved it

### Steps to reproduce the issue

1. The player is given cosmetic permissions and the player starts using cosmetics.
2. while the player is playing using cosmetics, the permission of the cosmetics is removed
3. the server kicks the player
4. When the player entered after being kicked out, he lost all his inventory and food level

### Server version

This server is running Paper version git-Paper-256 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: e30b082)

### CosmeticsCore Version

CosmeticsCore version 1.0.5

### ProtocolLib Version

ProtocolLib version 5.0.0-SNAPSHOT-b602

### LoneLibs Version

LoneLibs version 1.0.21

### CosmeticsCore config.yml

```shell
lang: en
extract_default_assets: true
cosmetics:
  max_equippable:
    body: 3
    balloon: 2
wardrobe_room:
  camera:
    hide_actionbar_texts: true
    rotation:
      enabled: true
    zoom:
      enabled: false
      min: 2
    fade_effect: true
    location:
      world: survival
      x: 10198.555882197374
      y: 70.07611352463131
      z: 1626.699999988079
      yaw: 136.58643
      pitch: -8.821076
  mannequin:
    location:
      world: survival
      x: 10196.515000947978
      y: 69.0
      z: 1624.5919736206795
      yaw: -45.053375
      pitch: 2.6871595
  teleport_area:
    enter:
      world: survival
      pos1:
        x: 10198
        y: 65
        z: 1621
      pos2:
        x: 10194
        y: 66
        z: 1623
    exit_location:
      world: survival
      x: 10196.449227459032
      y: 65.0
      z: 1619.699999988079
      yaw: -177.63983
      pitch: -0.8153213
  gui:
    cursor_default: fermented_spider_eye:9000001
    cursor_rotate: fermented_spider_eye:9000002
    cursor_pointer: fermented_spider_eye:9000003
    dyeing_pointer: fermented_spider_eye:9100003
    tutorial_gui: fermented_spider_eye:9100004
    tutorial_gui_checked: fermented_spider_eye:9100005
    slots:
      colors:
        not_owned: 195,147,57
        owned: 56,67,100
        wearing: 57,70,195
        wearing_preview: 195,120,57
        max_amount_reached: 111,111,111
save:
  # Use only one at a time
  file:
    enabled: true
  mysql:
    enabled: false
    url: jdbc:mysql://my_url_database_69.com:3306/database_name
    username: username
    password: password
    table: cosmeticscore_saved
debug: false
```

### Screenshots/Videos (you can drag and drop files or paste links)

video example: https://www.xbox.com/play/media/LS8H9TYDS4

**Comment by LoneDev6** [comment]
Are you sure this is not caused by another plugin or special configuration?
My plugin doesn't edit player food level or remove inventory contents. Everything done by the plugin is purely made by packets, so it's purely graphical.

Please make sure you don't have a special setting or another plugin interfering.
