### ISSUE TITLE
Compatibility with some teleport plugins

### ISSUE THREAD

**Issue by AltarRiza** [PluginBugs/Issues-CosmeticsCore#68]
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### Discord tag (optional)

Athame#4912

### What happened?

If I type /t spawn while in the wardrobe, I become invisible. 

### Steps to reproduce the issue

Just bug

### Server version

1.17.1

### CosmeticsCore Version

1.0.5

### ProtocolLib Version

4.8.0

### LoneLibs Version

1.0.21

**Comment by LoneDev6** [comment]
Probably your teleport plugin doesn't trigger the teleport event for some reason.

**Comment by AltarRiza** [comment]
I use towny plugin for /t spawn

**Comment by LoneDev6** [comment]
Can you try other teleport commands to see if the bug happens anyway?

**Comment by AltarRiza** [comment]
I try /spawn with essentials no problem

**Comment by LlmDl** [comment]
Towny's /t spawn command is ran with a TeleportCause.COMMAND, what is your teleport listener listening for @LoneDev6 ?

**Comment by AltarRiza** [comment]
Also /n spawn is invisibility bug. I have a video https://clipchamp.com/watch/kxPtNokkvN0

**Comment by LoneDev6** [comment]
> Towny's /t spawn command is ran with a TeleportCause.COMMAND, what is your teleport listener listening for @LoneDev6 ?

Thanks for the info, I'll try to see if this could be the cause and keep you updated about my tests.

**Comment by LoneDev6** [comment]
> Towny's /t spawn command is ran with a TeleportCause.COMMAND, what is your teleport listener listening for @LoneDev6 ?

```java
    @EventHandler(ignoreCancelled = true, priority = EventPriority.MONITOR)
    private void onPlayerTeleport(PlayerTeleportEvent e)
```

I don't do any check on TeleportCause property.

**Comment by LlmDl** [comment]
I would consider using PLUGIN and COMMAND causes for your setup. Some plugins use PLUGIN, some use COMMAND, some use both (like Towny.) Since you're wanting to track teleports I would listen to both.

**Comment by LoneDev6** [comment]
> I only check this and cancel if true.

I already do that

**Comment by LlmDl** [comment]
You are checking if the TeleportCause is PLUGIN, but are you also checking if `e.getCause() == PlayerTeleportEvent.TeleportCause.COMMAND` ?

**Comment by LoneDev6** [comment]
It might be fixed in the upcoming update, please let me know as soon as I release the update.
