### ISSUE TITLE
Fonts not loading, interact listener seems to be buggy

### ISSUE THREAD

**Issue by MinecollYT** [PluginBugs/Issues-CosmeticsCore#70]
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### Discord tag (optional)

Jonas L. | Minecoll_YT#0741

### What happened?

Fonts in title and gui not loading, see thread: https://discord.com/channels/533407895010803753/1053411872864477225

### Steps to reproduce the issue

Install the plugin

### Server version

This server is running Paper version git-Paper-388 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: fc9ee65 on ver/1.18.2)

### CosmeticsCore Version

1.0.5

### ProtocolLib Version

5.0.0-SNAPSHOT-b607

### LoneLibs Version

1.0.21

### Error (optional)

```shell
none
```

### Screenshots/Videos (you can drag and drop files or paste links)

![image](https://user-images.githubusercontent.com/43142792/208962505-b96d3020-532c-48b9-9973-246b49d8ece0.png)
![image](https://user-images.githubusercontent.com/43142792/208962538-d5850ec8-d36a-4e02-811f-a1c7779115ce.png)

https://cdn.discordapp.com/attachments/1053411872864477225/1053665567535530024/cosmeticcore.mp4

**Comment by LoneDev6** [comment]
https://itemsadder.devs.beer/faq/identify-why-textures-are-not-shown

**Comment by MinecollYT** [comment]
And what's going on with the other bug?

**Comment by MinecollYT** [comment]
> https://itemsadder.devs.beer/faq/identify-why-textures-are-not-shown

there is no issue shown related to the fonts

**Comment by MinecollYT** [comment]
Correction - One single error is shown related to cosmetic core:
[20:42:07 ERROR]: [ItemsAdder] PNG 'z_cosmetics:cosmetics_slot' not found for model. File: /home/container/plugins/ItemsAdder/data/resource_pack/assets/z_cosmetics/models/cosmetics_slot.json

**Comment by LoneDev6** [comment]
There is definitely something wrong in your pack.
I literally just loaded a fresh copy of itemsadder and cosmeticscore, followed cosmetiscore tutorial and they load just fine.
This page helps you understand if there is any issue in your pack: https://itemsadder.devs.beer/faq/identify-why-textures-are-not-shown
Make sure to carefully analyze the log.

I really can't do anything else without having your pack.
