### ISSUE TITLE
Nag author

### ISSUE THREAD

**Issue by MinecollYT** [PluginBugs/Issues-CosmeticsCore#71]
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### Discord tag (optional)

Jonas L. | Minecoll_YT#0741

### What happened?

Warning on startup

### Steps to reproduce the issue

1. Install cc
2. (Enable debug)
3. Start server

### Server version

This server is running Paper version git-Paper-388 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: fc9ee65 on ver/1.18.2)

### CosmeticsCore Version

1.0.5

### ProtocolLib Version

5.0.0-SNAPSHOT-b607

### LoneLibs Version

1.0.21

### Error (optional)

```shell
[17:21:51 WARN]: Nag author(s): '[]' of 'CosmeticsCore' about their usage of System.out/err.print. Please use your plugin's logger instead (JavaPlugin#getLogger).
```

**Comment by LoneDev6** [comment]
Provide the full server log.

**Comment by LoneDev6** [comment]
Fixed in the upcoming version
