### ISSUE TITLE
Can't use IA :placeholder: in diplay name/lore 

### ISSUE THREAD

**Issue by Klover91** [PluginBugs/Issues-CosmeticsCore#74]
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### What happened?

i can't use IA placeholders in cosmetic display-name/lore..

### Steps to reproduce the issue

1. add a lore/display-name with any font placeholder (:example: or even %img_example%)
2. iazip and cosmetic config reload

### CosmeticsCore Version

1.0.5

### ProtocolLib Version

5.0.0 snapshot b608

### LoneLibs Version

1.0.22

### Screenshots/Videos (you can drag and drop files or paste links)

![image](https://user-images.githubusercontent.com/114626224/210425859-2ca9dcd6-27c7-4d81-9954-80f703c6bad0.png)

**Comment by LoneDev6** [comment]
Will be fixed in the next days, thanks.

**Comment by Klover91** [comment]
grazie <3
