### ISSUE TITLE
Is the color code not supported? / gamemode creative -> surival Hat evaporation

### ISSUE THREAD

**Issue by cats-love** [PluginBugs/Issues-CosmeticsCore#75]
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### What happened?

Color code does not apply to item title. In addition, the hat evaporates when switching from creative mode to survival mode.

### Steps to reproduce the issue

Same as above.

### CosmeticsCore Version

1.0.5

### ProtocolLib Version

#608

### LoneLibs Version

1.0.22

### Screenshots/Videos (you can drag and drop files or paste links)

![image](https://user-images.githubusercontent.com/87476958/210881018-fc372273-2251-448d-8505-35647fb15fac.png)
![image](https://user-images.githubusercontent.com/87476958/210881071-c978a126-2d98-4b9e-be74-1fdc01517186.png)

**Comment by cats-love** [comment]
https://youtu.be/XWmKqDc_Zrg

**Comment by LoneDev6** [comment]
Duplicate: https://github.com/PluginBugs/Issues-CosmeticsCore/issues/16

Also please don't put multiple issue reports in the same github page.
