### ISSUE TITLE
API-Method to hide Cosmetics temporarily and show them again

### ISSUE THREAD

**Issue by Gebuildet** [PluginBugs/Issues-CosmeticsCore#80]
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

Gebuildet#1289

### Describe the solution you'd like

An API method capable of temporarily hiding certain cosmetics and turning them back on later. When hidden, the cosmetics he was previously wearing will be sent to the MYSQL database, allowing developers to turn the cosmetics back on even if he changed servers.

### Is your feature request related to a problem?

When a server (e.g. a minigame network) puts its players in spectator mode, the cosmetics are still displayed to the other players and the spectator himself gets annoyed with the cosmetic core-sent armor stands standing right in front of his face while being visible because of spectator mode.

### Describe alternatives you've considered

There is no alternative which came to my mind.

**Comment by LoneDev6** [comment]
> When a server (e.g. a minigame network) puts its players in spectator mode, the cosmetics are still displayed

This is not normal, CosmeticsCore hides cosmetics when the player is in spectator mode.

**Comment by Gebuildet** [comment]
> > When a server (e.g. a minigame network) puts its players in spectator mode, the cosmetics are still displayed
> 
> This is not normal, CosmeticsCore hides cosmetics when the player is in spectator mode.

Even if this does only occur at our server: I believe it would be a great addition for the API, since developers then can finally hide the cosmetics in specific scenarios.

**Comment by LoneDev6** [comment]
Yes the API idea is good, but I want to know why you have this issue.
Are you setting spectator mode via packets?
Since if you call the Bukkit API you should not have this issue as CosmeticsCore catches the gamemode change event.

**Comment by Gebuildet** [comment]
> Yes the API idea is good, but I want to know why you have this issue. Are you setting spectator mode via packets? Since if you call the Bukkit API you should not have this issue as CosmeticsCore catches the gamemode change event.

I recently bought CinematicCore and theres actually the same issue i described. When i set the player into spectator mode, using gamemode spectator %player%, the cosmetics are still visible. However, when i type it in manually, the cosmetics disappear.

**Comment by LoneDev6** [comment]
What do you mean exactly by this?
> using gamemode spectator %player%

**Comment by Gebuildet** [comment]
> What do you mean exactly by this?
> 
> > using gamemode spectator %player%

Adding an effect which executes the command "gamemode spectator %player%", when starting a cutscene.

**Comment by LoneDev6** [comment]
I'll do some tests but this is very strange.
Thanks.

**Comment by LoneDev6** [comment]
Being worked on here https://github.com/PluginBugs/Issues-CinematicStudio/issues/51
