### ISSUE TITLE
BackPakcs Bugs

### ISSUE THREAD

**Issue by dinobossytnew** [PluginBugs/Issues-CosmeticsCore#81]
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### Discord tag (optional)

DinoBoss#6985

### What happened?

It seems that my backpack flies off.

### Steps to reproduce the issue

First step create the config that you are going to see below, I entered the sv to see everything was fine in the preview but then I saw it outside and it looks horrible.

### Server version

[15:57:36 INFO]: This server is running Paper version git-Paper-375 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 7a64b85)
You are running the latest version
Previous version: git-Paper-365 (MC: 1.19.3)

### CosmeticsCore Version

[16:20:24 INFO]: CosmeticsCore version 1.0.6-r4

### ProtocolLib Version

[15:57:30 INFO]: ProtocolLib version 5.0.0-SNAPSHOT-b608
[15:57:30 INFO]: Provides read/write access to the Minecraft protocol.
[15:57:30 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

[15:57:12 INFO]: LoneLibs version 1.0.23
[15:57:12 INFO]: Collection of libs used by my plugins
[15:57:12 INFO]: Authors: LoneDev and others

### FULL server log

https://mcpaste.io/8b4e9154ccb62343

ignore error for memory my localhost 9 gb ram xdd

### Error (optional)

```shell
not
```

### Problematic items yml configuration file (optional)

```shell
cosmetics:
  bear_set_backpack:
    display_name: "[Bear Set] Teddy BackPack"
    type: BODY_ITEM
    model:
      gui: bear_set:backpack
      normal: bear_set:backpack
      self: bear_set:backpack
    dye:
      enabled: false
      default: "#000000"
  bear_set_helmet:
    display_name: "[Bear Set] Teddy Helmet"
    type: HAT
    model:
      gui: bear_set:hood
      normal: bear_set:hood
    dye:
      enabled: false
      default: "#000000"
  bear_set_watermelon_flags:
    display_name: "[Bear Set] Teddy flags"
    type: BODY_ITEM
    model:
      gui: bear_set:flag
      normal: bear_set:flag
    dye:
      enabled: false
      default: "#000000"
  bear_set_teddybear:
    display_name: "[Bear Set] TeddyBear"
    type: HAT
    model:
      gui: bear_set:teddybear
      normal: bear_set:teddybear
    dye:
      enabled: false
      default: "#000000"
```

### Screenshots/Videos (you can drag and drop files or paste links)

![2023-01-10_15 51 56](https://user-images.githubusercontent.com/58078116/211640365-a25a1ea2-847e-40df-80d8-ae77516d7de2.png)
![2023-01-10_15 52 37](https://user-images.githubusercontent.com/58078116/211640373-7a9c2be6-c8b9-461b-88f2-44bcb919fd78.png)

video https://vimeo.com/788030769

**Comment by LoneDev6** [comment]
Are you sure you followed the tutorial carefully?
Are my example backpacks working fine? https://cosmeticscore.devs.beer/first-install/install-base-resourcepack

**Comment by dinobossytnew** [comment]
No, it doesn't happen with the normal backpacks, do you think it is something about the configuration or the model?

**Comment by LoneDev6** [comment]
Absolutely, it's caused by a misconfiguration of your custom backpacks.
Check them in blockbench and make sure to use the CosmeticsCore extension.
https://cosmeticscore.devs.beer/adding-content/body-item/static-body-item/normal-and-self-models

Follow the guide carefully.
