### ISSUE TITLE
Cosmetic error

### ISSUE THREAD

**Issue by PasteDev** [PluginBugs/Issues-CosmeticsCore#84]
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### Discord tag (optional)

Pastelito#9505

### What happened?

Hello, I have a problem, I created a cosmetic but when I put it on, only I see it and not the rest of the players. Can anyone have an idea of ​​why it is? no errors in console

### Steps to reproduce the issue

[Desktop.zip](https://github.com/PluginBugs/Issues-CosmeticsCore/files/10396904/Desktop.zip)

### Server version

![image](https://user-images.githubusercontent.com/42726698/211944528-56764a74-957d-4812-b8b0-a462968fe166.png)

### CosmeticsCore Version

![image](https://user-images.githubusercontent.com/42726698/211944564-e150207e-31ad-46cd-ae48-aa698e48d615.png)

### ProtocolLib Version

![image](https://user-images.githubusercontent.com/42726698/211944649-f23a4cfd-82c6-4340-9619-6e6b78d3a2d7.png)

### LoneLibs Version

![image](https://user-images.githubusercontent.com/42726698/211944690-abca4b93-09e8-4194-85e9-fb77bf6770f9.png)

**Comment by LoneDev6** [comment]
Make sure that the example pack work. If the example pack works then you had made a mistake in your configurations.
Follow the wiki guides https://cosmeticscore.devs.beer/adding-content

I think that you have set a bad `normal` model. Make sure to read: https://cosmeticscore.devs.beer/adding-content/body-item/static-body-item/normal-and-self-models

It's all clearly explained.

**Comment by PasteDev** [comment]
I already tried redoing the model in blockbench and it doesn't work
I even tried a thousand ways and this even happened to me

me:
![image](https://user-images.githubusercontent.com/42726698/212106971-89df8459-9401-494c-9ba9-72068d7fb3c8.png)

other:
![image](https://user-images.githubusercontent.com/42726698/212107081-bee0d47e-21ee-43bd-96a8-b6915442e119.png)


and this:

me: 
![image](https://user-images.githubusercontent.com/42726698/212107484-1201f2c8-3173-406f-a2f7-f87ee7037815.png)


and other: 
![image](https://user-images.githubusercontent.com/42726698/212107417-145cf093-6d5f-4a8c-b62b-94b2b2132c1c.png)

**Comment by PasteDev** [comment]
[meowmi.zip](https://github.com/PluginBugs/Issues-CosmeticsCore/files/10403127/meowmi.zip)
These are the "self" files in case you can take a look, according to me I followed the steps well

**Comment by LoneDev6** [comment]
I'll try to fix it for you as soon as I can.
Please share all the files you have for this cosmetic, also the normal model json.

**Comment by PasteDev** [comment]
Sorry, I was able to fix it, it was an error in the original texture, I already found the error, thank you very much anyway

**Comment by PasteDev** [comment]
And by the way, I ask you, is there a way to completely avoid the tutorial message when you enter the area where you put the cosmetics? I wish that didn't come out or there is an option in config.yml to turn it off

**Comment by LoneDev6** [comment]
> Sorry, I was able to fix it, it was an error in the original texture, I already found the error, thank you very much anyway

Amazing!



> And by the way, I ask you, is there a way to completely avoid the tutorial message when you enter the area where you put the cosmetics? I wish that didn't come out or there is an option in config.yml to turn it off

Not really since people will surely annoy you with questions to know how the system works.
The tutorial GUI is shown only if you the player doesn't click the button to accept the tutorial, it will make it disappear.

**Comment by PasteDev** [comment]
Another idea that occurs to me is that perhaps a "BlockFloodgate" function can be implemented, as well as when they do not have permissions, users cannot enter, that when this option is activated, bedrock players are not allowed to enter, in my opinion It would help me a lot since half of my players are from that platform

and as a very exaggerated idea to do as a "support" with custom menus in bedrock, a style like that
https://github.com/kejonaMC/CrossplatForms/wiki/modal-form

They are just suggestions that as a client I would like to see implemented one day 😊
