### ISSUE TITLE
Balloons block view or interfere with play.

### ISSUE THREAD

**Issue by Ecilpse** [PluginBugs/Issues-CosmeticsCore#86]
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Describe the solution you'd like

Same as the title.

### Is your feature request related to a problem?

Balloons block view or interfere with play. Therefore, players have a low preference for that cosmetics.

### Describe alternatives you've considered

It seems that convenience needs to be improved so that it is not blocked or uncomfortable.

**Comment by LoneDev6** [comment]
Please share some screenshots to show how obstructing balloons are on your server

**Comment by Ecilpse** [comment]
> Please share some screenshots to show how obstructing balloons are on your server

like this. i tried to pull arrow (right click) all directions,
However, when the crosshair is close to the balloon, it does not right-click.
problems is occur all of activities, not just when shooting an arrow.

This phenomenon is so intrusive and uncomfortable that players don't try to use balloons.

**Comment by Lerphie** [comment]
> > Please share some screenshots to show how obstructing balloons are on your server
> 
> like this. i tried to pull arrow (right click) all directions, However, when the crosshair is close to the balloon, it does not right-click. problems is occur all of activities, not just when shooting an arrow.
> 
> This phenomenon is so intrusive and uncomfortable that players don't try to use balloons.
> 
> youtube: https://youtu.be/GCMtyYTTmcE

I agree with you! I am also annoyed by this bug. Especially during pvp, wings and balloons interfere

**Comment by LoneDev6** [comment]
Thanks for the helpful video.
I will check this as soon as possible.

**Comment by LoneDev6** [comment]
I cannot reproduce the issue. Try with the vanilla client.
Also update CosmeticsCore to the latest version if you didn't.



https://github.com/PluginBugs/Issues-CosmeticsCore/assets/27242001/0dbea83a-00df-4b73-86db-6907036e5c10
