### ISSUE TITLE
Balloon hitbox problem 

### ISSUE THREAD

**Issue by haroldrc** [PluginBugs/Issues-CosmeticsCore#89]
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### What happened?

the balloon sometimes blocks the hit

### Steps to reproduce the issue

1. wear the balloon
2. get hit

### Server version

git-Pufferfish-42 (MC: 1.19.2)

### CosmeticsCore Version

1.0.7

### ProtocolLib Version

5.0.0-SNAPSHOT-b612

### LoneLibs Version

1.0.23

### Problematic items yml configuration file (optional)

```shell
ballon_cluster:
    display_name: "Ammasso di palloncini"
    type: BALLOON_ENTITY
    model:
      gui: potion:400015
      normal: cosmetics:ballon_cluster
    dye:
      enabled: false
```

### Screenshots/Videos (you can drag and drop files or paste links)

https://streamable.com/3xv62f

**Comment by haroldrc** [comment]
new problem: if you have a backpack you can't use the trident to fly

**Comment by LoneDev6** [comment]
Will be checked
