### ISSUE TITLE
exiting wardrobe with shift, BetonQuest issue

### ISSUE THREAD

**Issue by MrDraqon** [PluginBugs/Issues-CosmeticsCore#90]
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### Discord tag (optional)

Dragon#0666

### What happened?

Using this plugin https://www.spigotmc.org/resources/betonquest-all-your-adventure-supplies-versatile-quests-in-depth-conversations.2117/

talking with the npcs will prevent you from shift clicking out of the /wardrobe

i talked with the developers of that plugin and they cant say whats wrong since CosmeticsCore arent open sourced

### Steps to reproduce the issue

Talk with npc then go to the /wardrobe 
and shift click
a

### Server version

[04:26:55 INFO]: This server is running Paper version git-Paper-381 (MC: 1.19.3) 

### CosmeticsCore Version

[04:25:11 INFO]: CosmeticsCore version 1.2.0

### ProtocolLib Version

[04:20:10 INFO]: ProtocolLib version 5.0.0-SNAPSHOT-b612
[04:20:10 INFO]: Provides read/write access to the Minecraft protocol.
[04:20:10 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

[04:20:27 INFO]: LoneLibs version 1.0.23
[04:20:27 INFO]: Collection of libs used by my plugins
[04:20:27 INFO]: Authors: LoneDev and others

### Screenshots/Videos (you can drag and drop files or paste links)

https://www.dropbox.com/s/l4xpueosdc1qiy5/Minecraft%202023.01.31%20-%2001.29.28.01.mp4?dl=1

**Comment by LoneDev6** [comment]
I tried to setup a simple quest but I can't manage to understand the wiki.
Please provide a proper configuration folder for Beton quest that I can drag and drop to test.

I tried this but right clicking the NPC doesn't work at all.
[test.zip](https://github.com/PluginBugs/Issues-CosmeticsCore/files/10845167/test.zip)

**Comment by MrDraqon** [comment]
> I tried to setup a simple quest but I can't manage to understand the wiki. Please provide a proper configuration folder for Beton quest that I can drag and drop to test.
> 
> I tried this but right clicking the NPC doesn't work at all. [test.zip](https://github.com/PluginBugs/Issues-CosmeticsCore/files/10845167/test.zip)

If you donwloaded their latest from spigot then the wiki wont make sense you need to use the latest dev version they changed how its setup 

Unzip the attached file into plugins/BetonQuest/QuestPackages 
Then open package.yml  and spawn a NPC with citizens and add its id to the 'npcs' list 

Tried asking them for help as well but they say they cant fix it because CosmeticsCore is closed source

**Comment by MrDraqon** [comment]
> Cannot reproduce the issue, I dragged and dropped your configurations into my betonquest folder (clean folder). If you have any other customized setting in other Betonquest yml files please share them. https://streamable.com/usdqr0

My BretonQuest is default all i have done is setup the conversation/quest i send you to figure out how it worked

Just updated to Latest CosmeticsCore and BretonQuest and i am still having the issue ill try them on a clean server install with only the necessary plugins they need and see if some other plugin might be an issue.

**Comment by LoneDev6** [comment]
The only difference is that i'm using the menu instead of the chat dialogue.
I have no idea of how to switch between them since the menu seems to be the default one on betonquest installation.
