### ISSUE TITLE
Can't see any clothing items in the closet

### ISSUE THREAD

**Issue by madebygood** [PluginBugs/Issues-CosmeticsCore#91]
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### What happened?

After updating to 1.2.0, I can't see any items in my closet. (Even with OP authority)

When I downgrade back to 1.0.7, it looks fine.

### Steps to reproduce the issue

REDACTED

this is my config file

### Server version

![image](https://user-images.githubusercontent.com/43653581/216215935-9b230483-39c4-4327-bb5a-40b2079bf82f.png)

### CosmeticsCore Version

1.2.0

### ProtocolLib Version

5.0.0 - b612

### LoneLibs Version

1.0.23

**Comment by reneg1990** [comment]
Hi! I just updated as well (from 1.0.5 to 1.2.0) and I am having the exact same issue, no cosmetics shows up in any of the UIs.

**Comment by LoneDev6** [comment]
Can you make a video?
Did you set the player permissions?
https://cosmeticscore.devs.beer/permissions

**Comment by reneg1990** [comment]
Maybe OP can make a video - i cant right now as I am at work.

My permissions are personally set up correct as its been used on a live server for 3-4 months now with no issues. Its the upgrade from 1.0.5 -> 1.2.0 that made all the cosmetics dissapear in the UI.

**Comment by madebygood** [comment]
> 
Players who have all permissions and are OP will not see any cosmetic items.

The resource pack is well applied.

I've been using it for a few months without any problems, but since 1.2.0 I've had a problem.

**Comment by FreddieDK** [comment]
Same issue here, when I upgrade from 1.0.6 it doesn't work.

**Comment by LoneDev6** [comment]
As I said:
- post a video
- post a COMPLETE SERVER LOG of when the issue occurred

Without this info I cannot do anything.

**Comment by haroldrc** [comment]
same problem

**Comment by Osmanto123** [comment]
same problem

**Comment by MichyTwitch** [comment]
same

**Comment by LoneDev6** [comment]
It's because you did not set enabled: true in any of the cosmetics files.
The new update will make it default to true, now it's false.

Open all your cosmetics yml files inside the cosmeticscore folder and add `enabled: true` on each cosmetic.

Example: 
```yml
cosmetics:
  leather_backpack:
    enabled: true
    display_name: "Leather Backpack"
    type: BODY_ITEM
```
