### ISSUE TITLE
Several Visibility bugs with Bukkit#hidePlayer 

### ISSUE THREAD

**Issue by verklicktl** [PluginBugs/Issues-CosmeticsCore#92]
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if a solution is already known.
- I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### Discord tag (optional)

Verklickt#6795

### What happened?

1. While hiding players with Bukkit#hidePlayer, there Cosmetics are still visible.
2. After showing the players again, their baloons leash stays at the position the player was before.

### Steps to reproduce the issue

Related to 1. issue: 
1. Hide a player1 from a player2 with Bukkit#hidePlayer
2. The Cosmetics of the hidden player1 are still visible to player2.

Related to 2. issue:
1. Hide player1 with a baloon from a player2 with Bukkit#hidePlayer
2. The Baloon of the hidden player1 is still visible
3. Show the player1 with baloon to the player2 again
4. The player2 sees the player1s leash where it was before step 3.

### Server version

git-Purpur-1895

### CosmeticsCore Version

1.0.6-r2

### ProtocolLib Version

5.0.0-SNAPSHOT-b612

### LoneLibs Version

1.0.23

### FULL server log

Nothing to show there

### Error (optional)

```shell
-
```

### CosmeticsCore config.yml

```shell
lang: en
extract_default_assets: true
cosmetics:
  max_equippable:
    body: 3
    balloon: 2
wardrobe_room:
  camera:
    hide_actionbar_texts: true
    rotation:
      enabled: true
    zoom:
      enabled: true
      min: 2
    fade_effect: true
    location:
      world: world
      x: -39.5
      y: 72.0
      z: -225.5
      yaw: -180
      pitch: 0
  mannequin:
    location:
      world: world
      x: -39.5
      y: 71.0
      z: -231.5
      yaw: 0
      pitch: 0
  teleport_area:
    enter:
      world: world
      pos1:
        x: -39.0
        y: 113.0
        z: -219.0
      pos2:
        x: -41.0
        y: 110.0
        z: -219.0
    exit_location:
      world: world
      x: -39.5
      y: 111.0
      z: -216.5
      yaw: 0
      pitch: 0
  gui:
    cursor_default: fermented_spider_eye:9000001
    cursor_rotate: fermented_spider_eye:9000002
    cursor_pointer: fermented_spider_eye:9000003
    dyeing_pointer: fermented_spider_eye:9100003
    tutorial_gui: fermented_spider_eye:9100004
    tutorial_gui_checked: fermented_spider_eye:9100005
    slots:
      colors:
        not_owned: 195,147,57
        owned: 56,67,100
        wearing: 57,70,195
        wearing_preview: 195,120,57
        max_amount_reached: 111,111,111
save:
  # Use only one at a time
  file:
    enabled: true
  mysql:
    enabled: false
    url: jdbc:mysql://my_url_database_69.com:3306/database_name
    username: username
    password: password
    table: cosmeticscore_saved
debug: false
```

### Problematic items yml configuration file (optional)

```shell
-
```

### Other files, you can drag and drop them here to upload. (optional)

-

### Screenshots/Videos (you can drag and drop files or paste links)

![image](https://user-images.githubusercontent.com/90093249/216840683-9fcaf5f9-4e6f-4914-a1b9-8488b538f2db.png)
![image](https://user-images.githubusercontent.com/90093249/216840710-6238c436-9fe5-4780-82e9-c618f658446b.png)

**Comment by LoneDev6** [comment]
Will be checked, thanks
