### ISSUE TITLE
CosmeticsCodeApi#getEquippedCosmeticsKeys & #getEquippedCosmeticsAccessors returned lists

### ISSUE THREAD

**Issue by julian-siebert** [PluginBugs/Issues-CosmeticsCore#93]
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

Verklickt#6795

### Describe the solution you'd like

CosmeticsCodeApi#getEquippedCosmeticsKeys & CosmeticsCodeApi#getEquippedCosmeticsAccessors return just regular Lists.
I would like to see them returning a Stringlist and CosmeticAccessorsList to avoid the instanceof check.

### Is your feature request related to a problem?

-

### Describe alternatives you've considered

Return lists inherit to the object added into them

### Additional context

-

**Comment by Akiranya** [comment]
Afaik the API is still WIP and for now it always returns a list of `Strings` and `CosmeticAccessor` and you actually don't have to use `instanceof` for the check.

Just add the type parameter to your decalared variables and that's it:

```
List<String> keys = CosmeticsCodeApi#getEquippedCosmeticsKeys keys;
```

You can safely ignore the compiler warnings of "unchecked parameter"

**Comment by LoneDev6** [comment]
The API is a wip for now, do the cast.
I will provide a maven api in the future releases when the API will be polished.

Thanks
