### ISSUE TITLE
When wearing body decorations, can not get off the vehicle.

### ISSUE THREAD

**Issue by madebygood** [PluginBugs/Issues-CosmeticsCore#94]
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### What happened?

I Wearing body cosmetics.

Other players sit over my head with skript, gsit, etc.
![image](https://user-images.githubusercontent.com/43653581/216970202-038d02e4-1548-4e3e-9354-6f3d0066d576.png)

Then that player can't leave me. can never get off.

### Steps to reproduce the issue

When wearing no cosmetics:
1) Ride me to no cosmetics player.
![2023-02-06_21 13 14](https://user-images.githubusercontent.com/43653581/216968608-2948469f-b765-41f7-a9aa-d884cbd55832.png)

2) Press Shift in keyboard.
![image](https://user-images.githubusercontent.com/43653581/216968694-4a60421f-b193-40b7-bcf2-a3849abbb0fd.png)

Gets off the mount just fine.

When wearing body cosmetics:
1) Ride me to body cosmetics player.
![2023-02-06_21 16 59](https://user-images.githubusercontent.com/43653581/216969153-e601a5bf-17dd-4e70-ac48-91cf78b095c1.png)

2) Even if I press shift, fall into water, or teleport to another place
Never get off the mount.
![image](https://user-images.githubusercontent.com/43653581/216969344-04e36955-2e48-4f6f-b299-9308d271f929.png)

![image](https://user-images.githubusercontent.com/43653581/216969407-db679b38-6b16-499d-b982-fa736a68139d.png)

### Server version

![image](https://user-images.githubusercontent.com/43653581/216969732-68e6fe8c-3326-4bb4-b6f9-22559ee3c4f2.png)

### CosmeticsCore Version

1.0.7
(Version 1.2 cannot be used because no cosmetics are displayed.)

### ProtocolLib Version

5.0.0 - b612

### LoneLibs Version

1.0.23

**Comment by LoneDev6** [comment]
I doubt there is a way to fix this since the cosmetics are created using passengers.
I'll try to find a solution but I doubt it's possible.

**Comment by LoneDev6** [comment]
I cannot reproduce the issue.
https://streamable.com/zwfus9

**Comment by madebygood** [comment]
Gsit's method is to create an ArmorStand above the player's head and sit on it.

Sit directly in the player's head with Skript or plugins.

This bug occurs.

**Comment by madebygood** [comment]
> I cannot reproduce the issue. https://streamable.com/zwfus9
> 
> It's probably a bug of TAB. I can't really do much about it since I'm not its developer.
> 
> CosmeticsCore + ItemsAdder + GSit = no issue.

Gsit's method is to create an ArmorStand above the player's head and sit on it.

Sit directly in the player's head with Skript or plugins.

This bug occurs.

**Comment by LoneDev6** [comment]
> Sit directly in the player's head with Skript or plugins.

Well probably Gsit does that to avoid this kind of issues I guess.
