### ISSUE TITLE
A plugin conflict with Triton

### ISSUE THREAD

**Issue by Xiaobonor** [PluginBugs/Issues-CosmeticsCore#95]
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### Discord tag (optional)

`小波#0001`

### What happened?

When I use Triton's GUI and the titles placeholder there is an error display

### Steps to reproduce the issue

1. Install Triton and  CosmeticsCore
2. Setup all
3. error reproduction

### Server version

This server is running Paper version git-Paper-386 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 4da844f)
You are 10 version(s) behind
Download the new version at: https://papermc.io/downloads
Previous version: git-Paper-307 (MC: 1.19.2)

### CosmeticsCore Version

CosmeticsCore 1.2.0

### ProtocolLib Version

ProtocolLib 5.0.0 - b612

### LoneLibs Version

LoneLibs 1.0.23

### Screenshots/Videos (you can drag and drop files or paste links)

https://cdn.discordapp.com/attachments/1020624008036749332/1074240676910350406/2023-02-12_16-06-58.mp4

**Comment by LoneDev6** [comment]
Please provide more information, the provided content expired.
