### ISSUE TITLE
remove backpack on swim and on fly

### ISSUE THREAD

**Issue by DanyGreaver** [PluginBugs/Issues-CosmeticsCore#96]
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Describe the solution you'd like

swimming and flying with a backpack looks funny in third person
since most people go in third person when swimming and flying, i think it'd be better to check and remove the backpack.

### Is your feature request related to a problem?

-

### Describe alternatives you've considered

-

### Additional context

-

**Comment by LoneDev6** [comment]
Cosmetics which cannot rotate with body are already hidden.
The only shown ones are hats and itemsadder body cosmetics.

https://streamable.com/coyooi
https://streamable.com/abyeu8
