### ISSUE TITLE
oraxen support

### ISSUE THREAD

**Issue by yenteh12** [PluginBugs/Issues-CosmeticsCore#97]
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

suum#4532

### Describe the solution you'd like

Hello, im thinking of buying this but i dont see support of oraxen. Is oraxen possible or not?

### Is your feature request related to a problem?

Yes, because my server is setup with oraxen and it would be too much to change to itemsadder

### Describe alternatives you've considered

nothing just oraxen support !

**Comment by LoneDev6** [comment]
you can use the custommodeldata feature.
For example hats:
https://cosmeticscore.devs.beer/adding-content/hat

Read the wiki for more info.


Note: you must know how to use oraxen and how to get custommodeldata values for your items models, I won't be able to give you support on that since i'm not its author.

**Comment by yenteh12** [comment]
> you can use the custommodeldata feature. For example hats: https://cosmeticscore.devs.beer/adding-content/hat
> 
> Read the wiki for more info.
> 
> Note: you must know how to use oraxen and how to get custommodeldata values for your items models, I won't be able to give you support on that since i'm not its author.

Thank you for the reply!
Modeldate could work indeed thanks for the tip !
