### ISSUE TITLE
When teleporting using BetterRTP, BODY ITEM's disappear and don't come back.

### ISSUE THREAD

**Issue by MustafaLKSZ** [PluginBugs/Issues-CosmeticsCore#98]
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same issue was already reported.
- [x] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### Discord tag (optional)

MustafaSZ#4009

### What happened?

If you use BetterRTP plugin's RTP  wearing a body cosmetic, said body cosmetic disappears and never comes back.

### Steps to reproduce the issue

1.) equip a BODY_ITEM
2.) Use /rtp [BetterRTP]
end

### Server version

This server is running Purpur version git-Purpur-1171 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

### CosmeticsCore Version

CosmeticsCore version 1.2.0

### ProtocolLib Version

ProtocolLib version 5.0.0-SNAPSHOT-b608

### LoneLibs Version

LoneLibs version 1.0.22

### FULL server log

[latest.log](https://github.com/PluginBugs/Issues-CosmeticsCore/files/10734475/latest.log)

### CosmeticsCore config.yml

```shell
lang: en
extract_default_assets: true
cosmetics:
  max_equippable:
    body: 3
    balloon: 2
wardrobe_room:
  camera:
    hide_actionbar_texts: true
    rotation:
      enabled: true
    zoom:
      enabled: true
      min: 2
    fade_effect: true
    location:
      world: world
      x: -28.22776190134676
      y: 179.62000000476837
      z: 41.19117313121091
      yaw: 299.10794
      pitch: -5.114663
  mannequin:
    location:
      world: world
      x: -25.412559813745936
      y: 178.0
      z: 43.09740891810932
      yaw: 122.5535
      pitch: 1.5104063
  teleport_area:
    enter:
      world: world
      pos1:
        x: -29.0
        y: 179.0
        z: 39.0
      pos2:
        x: -29.0
        y: 178.0
        z: 42.0
    exit_location:
      world: world
      x: -33.165350167314344
      y: 178.0
      z: 37.45874009024709
      yaw: -35.90779
      pitch: 8.766404
  gui:
    cursor_default: fermented_spider_eye:9000001
    cursor_rotate: fermented_spider_eye:9000002
    cursor_pointer: fermented_spider_eye:9000003
    dyeing_pointer: fermented_spider_eye:9100003
    tutorial_gui: fermented_spider_eye:9100004
    tutorial_gui_checked: fermented_spider_eye:9100005
    slots:
      colors:
        not_owned: 195,147,57
        owned: 56,67,100
        wearing: 57,70,195
        wearing_preview: 195,120,57
        max_amount_reached: 111,111,111
save:
  file:
    enabled: true
  mysql:
    enabled: false
    url: jdbc:mysql://my_url_database_69.com:3306/database_name
    username: username
    password: password
    table: cosmeticscore_saved
debug: false
send_creative_hidden_hat_message: true
```

### Problematic items yml configuration file (optional)

```shell
all BODY_ITEM
```

### Screenshots/Videos (you can drag and drop files or paste links)

https://clipchamp.com/watch/InYs8LFUo49

**Comment by LoneDev6** [comment]
I cannot reproduce it. Another plugin might be interfering. Remove all and keep only CosmeticsCore and its dependencies.
https://streamable.com/npat2y
